export const dataDosen = [
  {
    NIDN: "0410066303",
    NUPTK: 5942741642130122,
    namaDosen: "ANDY YUNIARSO",
    namaDosenGelar: "Andy Yuniarso, SE., MM., MBA.",
    programStudi: "Akuntansi (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "05 February 2018",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "Magister Manajemen",
    pendidikanS3: "",
  },
  {
    NIDN: "0422059502",
    NUPTK: 2854773674230242,
    namaDosen: "DANIA MEIDA ROSYIDAH",
    namaDosenGelar: "Dania Meida Rosyidah, S.Ak., M.Ak.",
    programStudi: "Akuntansi (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 January 2024",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Akuntansi",
    pendidikanS3: "",
  },
  {
    NIDN: 1515129301,
    NUPTK: 4547771672230313,
    namaDosen: "DEA ARME TIARA HARAHAP",
    namaDosenGelar: "Dea Arme Tiara Harahap, S.Ak., M.Ak.",
    programStudi: "Akuntansi (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "02 May 2024",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "Magister Akuntansi",
    pendidikanS3: "",
  },
  {
    NIDN: "0416066602",
    NUPTK: 2948744645230142,
    namaDosen: "ELIN PAULINA",
    namaDosenGelar: "Dra. Elin Paulina, M.M.",
    programStudi: "Akuntansi (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 April 2023",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Manajemen",
    pendidikanS3: "",
  },
  {
    NIDN: "0419118903",
    NUPTK: 1451767668230243,
    namaDosen: "HELIANI",
    namaDosenGelar: "Heliani, S.E., M.Ak.",
    programStudi: "Akuntansi (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 September 2022",
    Inpassing: "Penata Tk. I, golongan ruang III/d",
    tmtInpassing: "",
    pendidikanS2: "Magister Akuntansi",
    pendidikanS3: "",
    jabatan_struktural: "Ketua Prodi Akuntansi",
  },
  {
    NIDN: "0428047904",
    NUPTK: 8760757658130132,
    namaDosen: "IRWAN HERMAWAN",
    namaDosenGelar: "Irwan Hermawan, S.E., M.E.",
    programStudi: "Akuntansi (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 October 2019",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Ekonomi",
    pendidikanS3: "",
  },
  {
    NIDN: "0425119401",
    NUPTK: 9457772673230252,
    namaDosen: "MEUTIA RIANY",
    namaDosenGelar: "Meutia Riany, S.E., M.Ak.",
    programStudi: "Akuntansi (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 June 2023",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Akuntansi",
    pendidikanS3: "",
  },
  {
    NIDN: "0412079302",
    NUPTK: 3044771672130373,
    namaDosen: "MUHAMMAD ZULVAN DWI HATMOKO",
    namaDosenGelar: "Muhammad Zulvan Dwi Hatmoko, S.E., M.Acc.",
    programStudi: "Akuntansi (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 April 2024",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Akuntansi",
    pendidikanS3: "",
  },
  {
    NIDN: 8992810021,
    NUPTK: 9450760661130172,
    namaDosen: "MULUS WIJAYA KUSUMA",
    namaDosenGelar: "Mulus Wiajaya Kusuma, S.E., M.Ec.Dev., Ph.D.",
    programStudi: "Akuntansi (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 August 2022",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "",
    pendidikanS2: "Magister Ekonomi",
    pendidikanS3: "",
  },
  {
    NIDN: "0410128303",
    NUPTK: 1542761662130263,
    namaDosen: "NANAN SUNANDAR",
    namaDosenGelar: "Nanan Sunandar, S.E., M.Akt.",
    programStudi: "Akuntansi (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 March 2023",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Akuntansi",
    pendidikanS3: "",
  },
  {
    NIDN: "0428069601",
    NUPTK: 2960774675230222,
    namaDosen: "NUR HIDAYAH KUSUMANINGRUM FADHILAH",
    namaDosenGelar: "Nur Hidayah Kusumaningrum Fadhillah, S.E., M.Ak.",
    programStudi: "Akuntansi (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 December 2024",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "",
    pendidikanS2: "Magister Akuntansi",
    pendidikanS3: "",
  },
  {
    NIDN: "0403089501",
    NUPTK: 2135773674130253,
    namaDosen: "NURUL RUSDIANSYAH",
    namaDosenGelar: "Nurul Rusdiansyah, S.Akun., M.Ak.",
    programStudi: "Akuntansi (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 November 2023",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Akuntansi",
    pendidikanS3: "",
  },
  {
    NIDN: "0421109402",
    NUPTK: 9353772673130212,
    namaDosen: "TAOFIK MUHAMMAD GUMELAR",
    namaDosenGelar: "Taofik Muhammad Gumelar, S.E., M.Ak.",
    programStudi: "Akuntansi (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 June 2025",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b;",
    tmtInpassing: "",
    pendidikanS2: "Magister Akuntansi",
    pendidikanS3: "",
  },
  {
    NIDN: "0120240046",
    NUPTK: "",
    namaDosen: "ANGEL ESMERALDA",
    namaDosenGelar: "Dr. Angel II Pornasdoro Esmeralda",
    programStudi: "Akuntansi (S1)",
    jabatanAkademik: "Lektor Kepala",
    tmtJad: "18 October 2024",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "Magister - Manajemen Bisnis",
    pendidikanS3: "Doktor - Manajemen Bisnis",
  },
  {
    NIDN: "0407128602",
    NUPTK: "0539764665231103",
    namaDosen: "AAN SETIAWATI",
    namaDosenGelar: "Aan Setiawati, S.Pd., M.Ds.",
    programStudi: "Desain Komunikasi Visual (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 January 2017",
    Inpassing: "Penata Muda Tk. I, Golongan Ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Desain",
    pendidikanS3: "",
  },
  {
    NIDN: "0431088506",
    NUPTK: "0163763664130173",
    namaDosen: "AGUS DARMAWAN",
    namaDosenGelar: "Agus Darmawan, S.Sn., M.Sn.",
    programStudi: "Desain Komunikasi Visual (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 December 2024",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "",
    pendidikanS2: "Magister Seni",
    pendidikanS3: "",
    jabatan_struktural: "Ketua Prodi Desain Komunikasi Visual",
  },
  {
    NIDN: 8951550022,
    NUPTK: 6939764665200002,
    namaDosen: "ASEP SUTISNA SANJAYA",
    namaDosenGelar: "Dr. Asep Sutisna Sanjaya, M.Pd.",
    programStudi: "Desain Komunikasi Visual (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "06 July 2021",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "Magister Pendidikan",
    pendidikanS3: "Doktor - Penelitian dan Evaluasi Pendidikan",
  },
  {
    NIDN: "0409077901",
    NUPTK: 7041757659200033,
    namaDosen: "ASEP WAHYUDIN",
    namaDosenGelar: "Asep Wahyudin , S.Sn. M.Sn.",
    programStudi: "Desain Komunikasi Visual (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 May 2016",
    Inpassing: "Penata Muda Tk. I, Golongan Ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Seni",
    pendidikanS3: "",
  },
  {
    NIDN: 8961550022,
    NUPTK: 2558742643200013,
    namaDosen: "BUDI SETIADI",
    namaDosenGelar: "Dr. Budi Setiadi, M.Pd.",
    programStudi: "Desain Komunikasi Visual (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "Magister Pendidikan",
    pendidikanS3: "Doktor Administrasi Pendidikan",
  },
  {
    NIDN: "0405029503",
    NUPTK: "0537773674130242",
    namaDosen: "FIRMAN MUTAQIN",
    namaDosenGelar: "Firman Mutaqin, S.Ds., M.Ds.",
    programStudi: "Desain Komunikasi Visual (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 November 2024",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Desain",
    pendidikanS3: "",
  },
  {
    NIDN: "0408068805",
    NUPTK: 6940766667220012,
    namaDosen: "GESNIDA YUNITA",
    namaDosenGelar: "Gesnida Yunita, S.Sn., M.Sn.",
    programStudi: "Desain Komunikasi Visual (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 March 2023",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b;",
    tmtInpassing: "",
    pendidikanS2: "Magister Seni",
    pendidikanS3: "",
  },
  {
    NIDN: 8910060022,
    NUPTK: 5052755658200003,
    namaDosen: "HERWAN",
    namaDosenGelar: "Dr. Herwan, S.Pd.I., M.M.Pd.",
    programStudi: "Desain Komunikasi Visual (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "25 June 2021",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "Magister Manajemen Pendidikan",
    pendidikanS3: "Doktor Pendidikan Islam",
  },
  {
    NIDN: "0409107907",
    NUPTK: 1242757659300063,
    namaDosen: "ICUH KOMALA",
    namaDosenGelar: "Icuh Komala, S.Sn., M.Sn.",
    programStudi: "Desain Komunikasi Visual (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 October 2019",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Seni",
    pendidikanS3: "",
  },
  {
    NIDN: 9990518873,
    NUPTK: 5748762663231082,
    namaDosen: "IRNI RESMI APRIYANTI",
    namaDosenGelar: "Irni Resmi Apriyanti, S.Ds., M.Ds.",
    programStudi: "Desain Komunikasi Visual (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "01 August 2024",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "Magister Desain",
    pendidikanS3: "",
  },
  {
    NIDN: "",
    NUPTK: 3542776677130052,
    namaDosen: "IRVING GUSTAV SALIM, S.PD.",
    namaDosenGelar: "Irving Gustav Salim, S.Pd., M.Ds.",
    programStudi: "Desain Komunikasi Visual (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "01 August 2024",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "Magister Desain",
    pendidikanS3: "",
  },
  {
    NIDN: "0408108704",
    NUPTK: 2440765666130263,
    namaDosen: "MOCHAMAD FICKY AULIA",
    namaDosenGelar: "Mochamad Ficky Aulia, S.Ds., M.Sn.",
    programStudi: "Desain Komunikasi Visual (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 June 2024",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "",
    pendidikanS2: "Magister Seni",
    pendidikanS3: "",
  },
  {
    NIDN: "0419128603",
    NUPTK: "",
    namaDosen: "PRAWIRA YUDHA MAPPALAHERE",
    namaDosenGelar: "Prawira Yudha Mappalahere, S.T., M.Ds.",
    programStudi: "Desain Komunikasi Visual (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 January 2017",
    Inpassing: "Penata Muda Tk. I Golongan III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Desain",
    pendidikanS3: "",
  },
  {
    NIDN: "0422079203",
    NUPTK: 4054770671230313,
    namaDosen: "RARAY ISTIANAH",
    namaDosenGelar: "Raray Istianah S.Pd., M.Pd.",
    programStudi: "Desain Komunikasi Visual (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 January 2021",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Pendidikan",
    pendidikanS3: "",
  },
  {
    NIDN: "0416019501",
    NUPTK: 2448773674130202,
    namaDosen: "RIFKY NUGRAHA",
    namaDosenGelar: "Rifky Nugraha, S.Pd., M.Ds.",
    programStudi: "Desain Komunikasi Visual (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 November 2024",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Desain",
    pendidikanS3: "",
  },
  {
    NIDN: "0430109501",
    NUPTK: 7362773674130233,
    namaDosen: "TULUS REGA WAHYUNI E",
    namaDosenGelar: "Tulus Rega Wahyuni E, S.Kom.I., M.Sn.",
    programStudi: "Desain Komunikasi Visual (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 January 2023",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Seni",
    pendidikanS3: "",
  },
  {
    NIDN: 8971550022,
    NUPTK: 6445751652300022,
    namaDosen: "WATI SOLIHAT SUKMAWATI",
    namaDosenGelar: "Dr. Wati Solihat Sukmawati., S.S., M.M.Pd.",
    programStudi: "Desain Komunikasi Visual (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "07 July 2021",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "Magister Manajemen Pendidikan",
    pendidikanS3: "Doktor Sastra",
  },
  {
    NIDN: "0426069302",
    NUPTK: 7958771672130342,
    namaDosen: "ARMANSYAH",
    namaDosenGelar: "",
    programStudi: "Hukum (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 November 2023",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Hukum",
    pendidikanS3: "",
  },
  {
    NIDN: "0420057201",
    NUPTK: "0846765666131172",
    namaDosen: "BRAM BACHRUM BAAN",
    namaDosenGelar: "",
    programStudi: "Hukum (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 May 2024",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "",
    pendidikanS2: "Magister Hukum",
    pendidikanS3: "Doktor Ilmu hukum",
  },
  {
    NIDN: "0414058705",
    NUPTK: "",
    namaDosen: "CEP SAEPUL ALAM TEDDY LESMANA",
    namaDosenGelar: "",
    programStudi: "Hukum (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 December 2022",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "",
    pendidikanS2: "Magister Hukum",
    pendidikanS3: "",
  },
  {
    NIDN: "0424019501",
    NUPTK: 6456773674230222,
    namaDosen: "ENDAH PERTIWI",
    namaDosenGelar: "",
    programStudi: "Hukum (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 July 2023",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Kenotariatan",
    pendidikanS3: "",
    jabatan_struktural: "Ketua Prodi Hukum",
  },
  {
    NIDN: "0411068302",
    NUPTK: 5943761662130222,
    namaDosen: "FERDY FERDIAN",
    namaDosenGelar: "",
    programStudi: "Hukum (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "19 February 2010",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "Magister Ilmu Hukum",
    pendidikanS3: "",
  },
  {
    NIDN: 8986580023,
    NUPTK: "",
    namaDosen: "HAPPY DAVID PRADHAN",
    namaDosenGelar: "",
    programStudi: "Hukum (S1)",
    jabatanAkademik: "Lektor Kepala",
    tmtJad: "1 July 2023",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "Magister hukum bisnis",
    pendidikanS3: "Doktor Ilmu Hukum",
  },
  {
    NIDN: "0407016701",
    NUPTK: 7439745646130102,
    namaDosen: "HERI HERIYANTO",
    namaDosenGelar: "",
    programStudi: "Hukum (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 May 2024",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "",
    pendidikanS2: "Magister Manajemen",
    pendidikanS3: "Doktor Ilmu Hukum",
  },
  {
    NIDN: "0403126302",
    NUPTK: 1535741642130093,
    namaDosen: "JUNAIDI",
    namaDosenGelar: "",
    programStudi: "Hukum (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "01 February 2018",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "",
    pendidikanS3: "",
  },
  {
    NIDN: "0417038708",
    NUPTK: "",
    namaDosen: "M. ROKEN FADLY. MK",
    namaDosenGelar: "",
    programStudi: "Hukum (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "01 September 2022",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "Magister Hukum",
    pendidikanS3: "Doktor Ilmu Hukum",
  },
  {
    NIDN: "0120240047",
    NUPTK: "",
    namaDosen: "MARCO MARCHETTI",
    namaDosenGelar: "",
    programStudi: "Hukum (S1)",
    jabatanAkademik: "Profesor",
    tmtJad: "",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "Magister",
    pendidikanS3: "Doktor Ilmu Hukum",
  },
  {
    NIDN: "0417019305",
    NUPTK: 4449771672130262,
    namaDosen: "MUHAMAD RIZKI ABDUL MALIK",
    namaDosenGelar: "",
    programStudi: "Hukum (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 June 2025",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Hukum",
    pendidikanS3: "",
  },
  {
    NIDN: "0429129602",
    NUPTK: 1561774675130173,
    namaDosen: "MUHAMMAD RIDHO SINAGA",
    namaDosenGelar: "",
    programStudi: "Hukum (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 July 2025",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Hukum",
    pendidikanS3: "",
  },
  {
    NIDN: "0402048801",
    NUPTK: 7734766667130322,
    namaDosen: "NUCHRAHA ALHUDA HASNDA",
    namaDosenGelar: "",
    programStudi: "Hukum (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 June 2025",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Hukum",
    pendidikanS3: "",
  },
  {
    NIDN: "0401067608",
    NUPTK: "",
    namaDosen: "PADLILAH",
    namaDosenGelar: "",
    programStudi: "Hukum (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 May 2024",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "",
    pendidikanS2: "Magister Hukum",
    pendidikanS3: "Doktor Ilmu Hukum",
  },
  {
    NIDN: "0413066805",
    NUPTK: "",
    namaDosen: "RAHMATSYAH",
    namaDosenGelar: "",
    programStudi: "Hukum (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 July 2023",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "",
    pendidikanS2: "Magister Hukum",
    pendidikanS3: "Doktor Ilmu Hukum",
  },
  {
    NIDN: "0415098002",
    NUPTK: 8247758659230213,
    namaDosen: "RIDA ISTA SITEPU",
    namaDosenGelar: "",
    programStudi: "Hukum (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 October 2022",
    Inpassing: "Penata Tk. I, golongan ruang III/d",
    tmtInpassing: "",
    pendidikanS2: "Magister Hukum",
    pendidikanS3: "",
  },
  {
    NIDN: "0405058002",
    NUPTK: "",
    namaDosen: "RR. DEWI ANGGRAENI",
    namaDosenGelar: "",
    programStudi: "Hukum (S1)",
    jabatanAkademik: "Profesor",
    tmtJad: "1 November 2023",
    Inpassing: "Pembina, golongan ruang IV/a",
    tmtInpassing: "",
    pendidikanS2: "Magister Hukum",
    pendidikanS3: "Doktor Ilmu Hukum",
  },
  {
    NIDN: "0120240064",
    NUPTK: "",
    namaDosen: "SARITA NANDMEHAR,",
    namaDosenGelar: "",
    programStudi: "Hukum (S1)",
    jabatanAkademik: "Lektor Kepala",
    tmtJad: "",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "Magister Hukum",
    pendidikanS3: "Doktor Ilmu Hukum",
  },
  {
    NIDN: 8988700020,
    NUPTK: 4835740641130092,
    namaDosen: "SUMARTA SETIADI",
    namaDosenGelar: "",
    programStudi: "Hukum (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "01 July 2020",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "Magister Hukum",
    pendidikanS3: "",
  },
  {
    NIDN: "0420129103",
    NUPTK: 5552769670130283,
    namaDosen: "UJANG BADRU JAMAN",
    namaDosenGelar: "",
    programStudi: "Hukum (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 December 2024",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "",
    pendidikanS2: "Magister Hukum",
    pendidikanS3: "",
  },
  {
    NIDN: "0409046201",
    NUPTK: 8741740641130072,
    namaDosen: "ZAENAL ABIDIN",
    namaDosenGelar: "",
    programStudi: "Hukum (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "04 February 2019",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "Magister Hukum",
    pendidikanS3: "",
  },
  {
    NIDN: "0206077202",
    NUPTK: "",
    namaDosen: "DEDEN WITARSYAH",
    namaDosenGelar: "",
    programStudi: "Informatika (S2)",
    jabatanAkademik: "Lektor Kepala",
    tmtJad: "1 June 2023",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/d",
    tmtInpassing: "",
    pendidikanS2: "Master of Engineering Science Electrical Engineering",
    pendidikanS3: "Doctor Of Pilosophy",
  },
  {
    NIDN: "0416127102",
    NUPTK: "",
    namaDosen: "DESHINTA ARROVA DEWI",
    namaDosenGelar: "",
    programStudi: "Informatika (S2)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 March 2000",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "Magister Teknik",
    pendidikanS3: "Doctor of Pilosophy",
  },
  {
    NIDN: "0415108006",
    NUPTK: "",
    namaDosen: "DINI OKTARINA DWI HANDAYANI",
    namaDosenGelar: "",
    programStudi: "Informatika (S2)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 October 2019",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "",
    pendidikanS2: "Master of Information Technology",
    pendidikanS3: "Doctor of Pilosophy",
  },
  {
    NIDN: "0418068505",
    NUPTK: "",
    namaDosen: "HARIS AL QODRI MAARIF",
    namaDosenGelar: "",
    programStudi: "Informatika (S2)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 August 2022",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "",
    pendidikanS2: "Master of Science",
    pendidikanS3: "Doctor of Pilosophy",
  },
  {
    NIDN: 8978490024,
    NUPTK: "",
    namaDosen: "HUANG GAN",
    namaDosenGelar: "",
    programStudi: "Informatika (S2)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 October 2021",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "Master of Engineering",
    pendidikanS3: "Ph. D. in Engineering ( Computer Engineering)",
  },
  {
    NIDN: "0406097702",
    NUPTK: "",
    namaDosen: "JELITA ASIAN.PH.D",
    namaDosenGelar: "",
    programStudi: "Informatika (S2)",
    jabatanAkademik: "Lektor Kepala",
    tmtJad: "1 June 2025",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/d",
    tmtInpassing: "",
    pendidikanS2: "",
    pendidikanS3: "Doctor of Pilosophy",
  },
  {
    NIDN: "0315046903",
    NUPTK: "",
    namaDosen: "MEDIA ANUGERAH AYU",
    namaDosenGelar: "",
    programStudi: "Informatika (S2)",
    jabatanAkademik: "Guru Besar",
    tmtJad: "1 December 2019",
    Inpassing: "Pembina Tingkat I, golongan ruang IV/b",
    tmtInpassing: "",
    pendidikanS2: "Master of Science",
    pendidikanS3: "Doctor of Philosophy",
  },
  {
    NIDN: "0323096491",
    NUPTK: "",
    namaDosen: "TEDDY MANTORO",
    namaDosenGelar: "",
    programStudi: "Informatika (S2)",
    jabatanAkademik: "Guru Besar",
    tmtJad: "1 October 2016",
    Inpassing: "Pembina Utama Madya, golongan ruang IV/d",
    tmtInpassing: "",
    pendidikanS2: "Master of Science",
    pendidikanS3: "Doctor of Philosophy",
  },
  {
    NIDN: "0424068107",
    NUPTK: "",
    namaDosen: "UMAR ADITIAWARMAN",
    namaDosenGelar: "",
    programStudi: "Informatika (S2)",
    jabatanAkademik: "Lektor Kepala",
    tmtJad: "1 April 2025",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "",
    pendidikanS2: "Master of Information Technology",
    pendidikanS3: "Doctor of Philosophy",
  },
  {
    NIDN: "0419077007",
    NUPTK: "",
    namaDosen: "ABU BAKAR",
    namaDosenGelar: "",
    programStudi: "Manajemen (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 June 2021",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Manajemen",
    pendidikanS3: "",
  },
  {
    NIDN: "0412089501",
    NUPTK: "",
    namaDosen: "AGUNG MAULANA",
    namaDosenGelar: "",
    programStudi: "Manajemen (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 July 2025",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Master of Arts",
    pendidikanS3: "",
  },
  {
    NIDN: "0414079101",
    NUPTK: "",
    namaDosen: "ANA YULIANA JASUNI",
    namaDosenGelar: "",
    programStudi: "Manajemen (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 December 2022",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Manajemen",
    pendidikanS3: "",
    jabatan_struktural: "Ketua Prodi Teknik Informatika",
  },
  {
    NIDN: "0428049204",
    NUPTK: "",
    namaDosen: "ANDRI ARDHIYANSYAH",
    namaDosenGelar: "",
    programStudi: "Manajemen (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 March 2025",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Master Administrasi Bisnis",
    pendidikanS3: "",
  },
  {
    NIDN: "0417098804",
    NUPTK: "",
    namaDosen: "ARIEF FIRMANTO",
    namaDosenGelar: "",
    programStudi: "Manajemen (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "02 May 2024",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "Magister Manajemen",
    pendidikanS3: "",
  },
  {
    NIDN: "0424108603",
    NUPTK: "",
    namaDosen: "BAGJA RAHMA PUTRA",
    namaDosenGelar: "",
    programStudi: "Manajemen (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 February 2023",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Manajemen",
    pendidikanS3: "",
  },
  {
    NIDN: "0405119301",
    NUPTK: "",
    namaDosen: "BONSE ARIS MANDALA PUTRA SIMANGUNSONG",
    namaDosenGelar: "",
    programStudi: "Manajemen (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 August 2025",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Manajemen",
    pendidikanS3: "",
  },
  {
    NIDN: "",
    NUPTK: 7658765666230252,
    namaDosen: "CHIQUITA MAHARANI",
    namaDosenGelar: "",
    programStudi: "Manajemen (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "1 December 2023",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "Magister Manajemen",
    pendidikanS3: "",
  },
  {
    NIDN: 8945420021,
    NUPTK: "",
    namaDosen: "DANA BUDIMAN",
    namaDosenGelar: "",
    programStudi: "Manajemen (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 April 2022",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "",
    pendidikanS2: "Magister Sains",
    pendidikanS3: "Doktor Ilmu Manajemen",
  },
  {
    NIDN: "0420028304",
    NUPTK: "",
    namaDosen: "FITRINA LESTARI",
    namaDosenGelar: "",
    programStudi: "Manajemen (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 January 2023",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Administrasi Bisnis",
    pendidikanS3: "",
  },
  {
    NIDN: 2125129404,
    NUPTK: "",
    namaDosen: "IKMALUL MIFTAH. Z",
    namaDosenGelar: "",
    programStudi: "Manajemen (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "1 December 2023",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "Magister Administrasi Bisnis",
    pendidikanS3: "",
  },
  {
    NIDN: "0413099803",
    NUPTK: "",
    namaDosen: "INTAN DEANIDA PRATIWI",
    namaDosenGelar: "",
    programStudi: "Manajemen (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 June 2025",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Manajemen",
    pendidikanS3: "",
  },
  {
    NIDN: "0429128506",
    NUPTK: "",
    namaDosen: "KALFAJRIN KURNIAJI",
    namaDosenGelar: "",
    programStudi: "Manajemen (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 June 2023",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Manajemen",
    pendidikanS3: "",
  },
  {
    NIDN: "0412118403",
    NUPTK: "",
    namaDosen: "KHARISMA",
    namaDosenGelar: "",
    programStudi: "Manajemen (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 July 2020",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Administrasi Bisnis",
    pendidikanS3: "",
  },
  {
    NIDN: "0402068703",
    NUPTK: "",
    namaDosen: "M. ANDRI JUNIANSYAH",
    namaDosenGelar: "",
    programStudi: "Manajemen (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 January 2023",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Manajemen",
    pendidikanS3: "",
  },
  {
    NIDN: "0404039601",
    NUPTK: "",
    namaDosen: "MARINA",
    namaDosenGelar: "",
    programStudi: "Manajemen (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 June 2023",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Manajemen",
    pendidikanS3: "",
  },
  {
    NIDN: "0406118804",
    NUPTK: "",
    namaDosen: "MAULITA LUTFIANI",
    namaDosenGelar: "",
    programStudi: "Manajemen (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 June 2023",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Manajemen",
    pendidikanS3: "",
  },
  {
    NIDN: "0320057406",
    NUPTK: "",
    namaDosen: "MEILIANI LUCKIETA",
    namaDosenGelar: "",
    programStudi: "Manajemen (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 June 2023",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "",
    pendidikanS2: "Magister Manajemen",
    pendidikanS3: "Doktor Manajemen",
  },
  {
    NIDN: "0406119301",
    NUPTK: "",
    namaDosen: "MUHAMAD WAHYU HAMIJAYA",
    namaDosenGelar: "",
    programStudi: "Manajemen (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 June 2023",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Manajemen",
    pendidikanS3: "",
  },
  {
    NIDN: "0428018004",
    NUPTK: "",
    namaDosen: "NIA SONANI",
    namaDosenGelar: "",
    programStudi: "Manajemen (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 December 2021",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "",
    pendidikanS2: "Magister Manajemen",
    pendidikanS3: "",
  },
  {
    NIDN: "0422029502",
    NUPTK: "",
    namaDosen: "REKA RAMADHAN",
    namaDosenGelar: "",
    programStudi: "Manajemen (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 June 2023",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Pendidikan",
    pendidikanS3: "",
  },
  {
    NIDN: "0403019204",
    NUPTK: "",
    namaDosen: "RENA YULIANA",
    namaDosenGelar: "",
    programStudi: "Manajemen (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 July 2023",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Ekonomi",
    pendidikanS3: "",
  },
  {
    NIDN: "0419069402",
    NUPTK: "",
    namaDosen: "RIYAN MIRDAN FARIS",
    namaDosenGelar: "",
    programStudi: "Manajemen (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 June 2025",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Sains",
    pendidikanS3: "",
  },
  {
    NIDN: "0408079005",
    NUPTK: "",
    namaDosen: "RR AMANNA DZIKRILLAH L L",
    namaDosenGelar: "",
    programStudi: "Manajemen (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 June 2025",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Administrasi Bisnis",
    pendidikanS3: "",
  },
  {
    NIDN: "0409058606",
    NUPTK: "",
    namaDosen: "SALIX FINI MARIS",
    namaDosenGelar: "",
    programStudi: "Manajemen (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 July 2023",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Manajemen",
    pendidikanS3: "",
  },
  {
    NIDN: 8983170023,
    NUPTK: "",
    namaDosen: "SATISH KUMAR DAMODAR",
    namaDosenGelar: "",
    programStudi: "Manajemen (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "Master of Engineering",
    pendidikanS3: "Doktor of Philosophy",
  },
  {
    NIDN: "0413129601",
    NUPTK: "",
    namaDosen: "SITI NUR AISYAH",
    namaDosenGelar: "",
    programStudi: "Manajemen (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 March 2025",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Master of Arts",
    pendidikanS3: "",
  },
  {
    NIDN: "0416107003",
    NUPTK: "",
    namaDosen: "SITTI HIKMAWATTY",
    namaDosenGelar: "",
    programStudi: "Manajemen (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "Magister Pendidikan",
    pendidikanS3: "Doktor ilmu manajemen",
  },
  {
    NIDN: "0404049302",
    NUPTK: "",
    namaDosen: "THESSA TRI ASTUTY",
    namaDosenGelar: "",
    programStudi: "Manajemen (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "12 January 2024",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "Magister Manajemen",
    pendidikanS3: "",
  },
  {
    NIDN: "0402056302",
    NUPTK: "",
    namaDosen: "UMAR MANSUR",
    namaDosenGelar: "",
    programStudi: "Manajemen (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 May 2007",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/a",
    tmtInpassing: "",
    pendidikanS2: "Magister Manajemen",
    pendidikanS3: "",
  },
  {
    NIDN: "0422029304",
    NUPTK: "",
    namaDosen: "VIRANIE DWI MONIKAWATIE",
    namaDosenGelar: "",
    programStudi: "Manajemen (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "01 March 2022",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "Magister Pendidikan",
    pendidikanS3: "",
  },
  {
    NIDN: "0404049105",
    NUPTK: "",
    namaDosen: "WAHYU MULYADI",
    namaDosenGelar: "",
    programStudi: "Manajemen (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 June 2024",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Sains",
    pendidikanS3: "",
  },
  {
    NIDN: "0410128201",
    NUPTK: "",
    namaDosen: "YULI DIANI RAHMAWATI",
    namaDosenGelar: "",
    programStudi: "Manajemen (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "01/09/2023",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "Magister Manajemen",
    pendidikanS3: "",
  },
  {
    NIDN: "0317086202",
    NUPTK: "",
    namaDosen: "GUSTIAN DJUANDA",
    namaDosenGelar: "",
    programStudi: "Manajemen (S2)",
    jabatanAkademik: "Lektor Kepala",
    tmtJad: "1 May 2009",
    Inpassing: "Pembina, golongan ruang IV/a",
    tmtInpassing: "",
    pendidikanS2: "Magister Manajemen",
    pendidikanS3: "Doktor Ekonomi Islam",
  },
  {
    NIDN: "0407036606",
    NUPTK: "",
    namaDosen: "HESRI MINTAWATI",
    namaDosenGelar: "",
    programStudi: "Manajemen (S2)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 May 2022",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "",
    pendidikanS2: "Magister Manajemen",
    pendidikanS3: "Doctor of Philosophy",
  },
  {
    NIDN: 8957560023,
    NUPTK: "",
    namaDosen: "KOESMAWAN",
    namaDosenGelar: "",
    programStudi: "Manajemen (S2)",
    jabatanAkademik: "Guru Besar",
    tmtJad: "1 December 2003",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "Master of Business Administration",
    pendidikanS3: "Doctor of Business Administration",
  },
  {
    NIDN: "0410087407",
    NUPTK: "0142752653130173",
    namaDosen: "KURNIAWAN",
    namaDosenGelar: "Dr. Kurniawan, S.T., M.Si., M.M.",
    programStudi: "Manajemen (S2)",
    jabatanAkademik: "Lektor Kepala",
    tmtJad: "1 July 2022",
    Inpassing: "Pembina, golongan ruang IV/a",
    tmtInpassing: "",
    pendidikanS2: "Magister Ilmu Administrasi, Magister Manajemen",
    pendidikanS3: "Doktor",
    jabatan_struktural: "Rektor Universitas Nusa Putra",
  },
  {
    NIDN: "0429087304",
    NUPTK: "",
    namaDosen: "NUR HASAN KURNIAWAN",
    namaDosenGelar: "",
    programStudi: "Manajemen (S2)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "19 April 2024",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "Magister Ilmu Profesi Jalur Profesi",
    pendidikanS3: "Doktor",
  },
  {
    NIDN: "0307028902",
    NUPTK: "",
    namaDosen: "SLAMET SUTRISNO",
    namaDosenGelar: "",
    programStudi: "Manajemen (S2)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 August 2025",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "Magister Manajemen",
    pendidikanS3: "Doktor",
  },
  {
    NIDN: "",
    NUPTK: 4355772673130273,
    namaDosen: "AGUS HENDRIYANTO",
    namaDosenGelar: "",
    programStudi: "Pedagogi (S2)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "12 September 2024",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "Magister Pendidikan",
    pendidikanS3: "Doktor - Pendidikan Matematika",
  },
  {
    NIDN: "0415087009",
    NUPTK: "",
    namaDosen: "AYI ABDURAHMAN",
    namaDosenGelar: "",
    programStudi: "Pedagogi (S2)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 April 2022",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "",
    pendidikanS2: "Magister Ilmu Pendidikan, Magister Manajemen",
    pendidikanS3: "Doctor Ilmu Pendidikan",
  },
  {
    NIDN: "0414090901",
    NUPTK: "",
    namaDosen: "DR H BARKAH SPD MPD",
    namaDosenGelar: "",
    programStudi: "Pedagogi (S2)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 March 2022",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "",
    pendidikanS2: "Magister Pendidikan",
    pendidikanS3: "Doktor - Pendidikan Bahasa Indonesia",
  },
  {
    NIDN: "0427118201",
    NUPTK: "",
    namaDosen: "DYAH LYESMAYA",
    namaDosenGelar: "",
    programStudi: "Pedagogi (S2)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 October 2019",
    Inpassing: "Penata, golongan ruang III/d",
    tmtInpassing: "",
    pendidikanS2: "Magister Pendidikan",
    pendidikanS3: "Doktor Pendidikan Dasar",
  },
  {
    NIDN: 8906160022,
    NUPTK: "",
    namaDosen: "MUHIBBIN SYAH",
    namaDosenGelar: "",
    programStudi: "Pedagogi (S2)",
    jabatanAkademik: "Guru Besar",
    tmtJad: "1 December 2010",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "Master of Educational Studies",
    pendidikanS3: "Doktor - Administrasi Pendidikan",
  },
  {
    NIDN: "0429126903",
    NUPTK: "",
    namaDosen: "UCU AGUSTINI SRI MULYANI",
    namaDosenGelar: "",
    programStudi: "Pedagogi (S2)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 June 2025",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "",
    pendidikanS2: "Magister Pendidikan",
    pendidikanS3: "Doktor - Manajemen Pendidiakn",
  },
  {
    NIDN: "8915420021",
    NUPTK: "",
    namaDosen: "UJANG SYARIP HIDAYAT",
    namaDosenGelar: "",
    programStudi: "Pedagogi (S2)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 April 2022",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "",
    pendidikanS2: "Magister Administrasi Pendidikan",
    pendidikanS3: "Doktor Ilmu Pendidikan",
  },
  {
    NIDN: "0401056501",
    NUPTK: "",
    namaDosen: "WIWIN WINARNI",
    namaDosenGelar: "",
    programStudi: "Pedagogi (S2)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 May 2022",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "",
    pendidikanS2: "Magister Manajemen Pendidikan",
    pendidikanS3: "Doctor Ilmu Pendidikan",
  },
  {
    NIDN: "0419047405",
    NUPTK: "",
    namaDosen: "WULAN WIDANINGSIH",
    namaDosenGelar: "",
    programStudi: "Pedagogi (S2)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "09 August 2021",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "Magister Pendidikan Bahasa",
    pendidikanS3: "Doktor - Manajemen Pendidikan",
  },
  {
    NIDN: "0411019503",
    NUPTK: "",
    namaDosen: "ANY ELVIA JAKFAR",
    namaDosenGelar: "",
    programStudi: "Pendidikan Guru Sekolah Dasar (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 November 2024",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Master of Arts",
    pendidikanS3: "",
  },
  {
    NIDN: 8898290019,
    NUPTK: "",
    namaDosen: "BUDI KURNIA",
    namaDosenGelar: "",
    programStudi: "Pendidikan Guru Sekolah Dasar (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 November 2022",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Pendidikan",
    pendidikanS3: "",
  },
  {
    NIDN: "0423109403",
    NUPTK: "",
    namaDosen: "DHEA ADELA",
    namaDosenGelar: "",
    programStudi: "Pendidikan Guru Sekolah Dasar (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 December 2024",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "",
    pendidikanS2: "Magister Pendidikan",
    pendidikanS3: "",
  },
  {
    NIDN: "0419078905",
    NUPTK: "",
    namaDosen: "DINDA ANDIANA",
    namaDosenGelar: "",
    programStudi: "Pendidikan Guru Sekolah Dasar (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 August 2022",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Pendidikan",
    pendidikanS3: "",
  },
  {
    NIDN: "0412039401",
    NUPTK: "",
    namaDosen: "FITRIA NURULAENI",
    namaDosenGelar: "",
    programStudi: "Pendidikan Guru Sekolah Dasar (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 December 2024",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "",
    pendidikanS2: "Magister Pendidikan",
    pendidikanS3: "",
  },
  {
    NIDN: 8930850022,
    NUPTK: "",
    namaDosen: "IA HIDARYA",
    namaDosenGelar: "",
    programStudi: "Pendidikan Guru Sekolah Dasar (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 March 2024",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "",
    pendidikanS2: "Magister Manajemen",
    pendidikanS3: "Doktor - Ilmu Pendidikan",
  },
  {
    NIDN: "0405088204",
    NUPTK: "",
    namaDosen: "IRFAN SOFIAN",
    namaDosenGelar: "",
    programStudi: "Pendidikan Guru Sekolah Dasar (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "04 October 2021",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "Magister Pendidikan",
    pendidikanS3: "",
  },
  {
    NIDN: 8815723420,
    NUPTK: "",
    namaDosen: "IWAN GUNAWAN",
    namaDosenGelar: "",
    programStudi: "Pendidikan Guru Sekolah Dasar (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "31 October 2018",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "Magister Manajemen",
    pendidikanS3: "",
  },
  {
    NIDN: "0409109502",
    NUPTK: "",
    namaDosen: "JOKO SUPRAPMANTO",
    namaDosenGelar: "",
    programStudi: "Pendidikan Guru Sekolah Dasar (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 December 2024",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Pendidikan",
    pendidikanS3: "",
  },
  {
    NIDN: 8861500016,
    NUPTK: "",
    namaDosen: "KOHAR PRADESA",
    namaDosenGelar: "",
    programStudi: "Pendidikan Guru Sekolah Dasar (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 March 2020",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "",
    pendidikanS2: "Magister Pendidikan",
    pendidikanS3: "Doktor - Pendidikan Umum",
  },
  {
    NIDN: "0401077707",
    NUPTK: "",
    namaDosen: "LINA HERLINA",
    namaDosenGelar: "",
    programStudi: "Pendidikan Guru Sekolah Dasar (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 July 2023",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "",
    pendidikanS2: "Magister Pendidikan",
    pendidikanS3: "",
  },
  {
    NIDN: "0423058902",
    NUPTK: "",
    namaDosen: "MELSYA FIRTIKASARI",
    namaDosenGelar: "",
    programStudi: "Pendidikan Guru Sekolah Dasar (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 July 2025",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Seni",
    pendidikanS3: "",
  },
  {
    NIDN: 2112067905,
    NUPTK: "",
    namaDosen: "MOHAMAD NAJIB",
    namaDosenGelar: "",
    programStudi: "Pendidikan Guru Sekolah Dasar (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 August 2022",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Pendidikan",
    pendidikanS3: "",
  },
  {
    NIDN: "0427039305",
    NUPTK: "",
    namaDosen: "RINALDI YUSUP",
    namaDosenGelar: "",
    programStudi: "Pendidikan Guru Sekolah Dasar (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 July 2024",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Pendidikan",
    pendidikanS3: "",
  },
  {
    NIDN: 8970670023,
    NUPTK: 7938740644200012,
    namaDosen: "SAJIDIN",
    namaDosenGelar: "Sajidin, S.Pd., M.M.Pd.",
    programStudi: "Pendidikan Guru Sekolah Dasar (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "01 September 2022",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "Magister Manajemen Pendidikan",
    pendidikanS3: "",
  },
  {
    NIDN: "0403048803",
    NUPTK: "3735766667130322",
    namaDosen: "SAMSUL PAHMI",
    namaDosenGelar: "Samsul Pahmi, M.Pd",
    programStudi: "Pendidikan Guru Sekolah Dasar (S1)",
    jabatanAkademik: "Lektor Kepala",
    tmtJad: "1 December 2023",
    Inpassing: "Penata Tk. I, golongan ruang III/d",
    tmtInpassing: "",
    pendidikanS2: "Magister Pendidikan",
    pendidikanS3: "",
    jabatan_struktural: "Plt. Wakil Rektor I Bidang Akademik",
  },
  {
    NIDN: "0429129401",
    NUPTK: "",
    namaDosen: "SHERYL MUTIARA PUTRI",
    namaDosenGelar: "",
    programStudi: "Pendidikan Guru Sekolah Dasar (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 June 2025",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Pendidikan",
    pendidikanS3: "",
  },
  {
    NIDN: 8971530021,
    NUPTK: "",
    namaDosen: "SRI ERWINI CHRISTINE",
    namaDosenGelar: "",
    programStudi: "Pendidikan Guru Sekolah Dasar (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 June 2022",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "",
    pendidikanS2: "Magister Manajemen Pendidikan",
    pendidikanS3: "Doktor - Adminstrasi Pendidikan",
  },
  {
    NIDN: "0425079003",
    NUPTK: "",
    namaDosen: "TEOFILUS ARDIAN HOPEMAN",
    namaDosenGelar: "",
    programStudi: "Pendidikan Guru Sekolah Dasar (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 March 2025",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Pendidikan",
    pendidikanS3: "",
  },
  {
    NIDN: "0428036102",
    NUPTK: "",
    namaDosen: "UTOMO",
    namaDosenGelar: "",
    programStudi: "Pendidikan Guru Sekolah Dasar (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 April 2024",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "",
    pendidikanS2: "Magister Manajemen",
    pendidikanS3: "",
    jabatan_struktural: "Ketua Prodi Pendidikan Guru Sekolah Dasar",
  },
  {
    NIDN: "0417049102",
    NUPTK: "",
    namaDosen: "ADHITIA ERFINA",
    namaDosenGelar: "",
    programStudi: "Sistem Informasi (S1)",
    jabatanAkademik: "Lektor Kepala",
    tmtJad: "1 February 2023",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "",
    pendidikanS2: "Magister Komputer",
    pendidikanS3: "",
  },
  {
    NIDN: "0424089206",
    NUPTK: "",
    namaDosen: "ARNY LATTU",
    namaDosenGelar: "",
    programStudi: "Sistem Informasi (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 March 2025",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Sistem Informasi",
    pendidikanS3: "",
  },
  {
    NIDN: 8925420021,
    NUPTK: "",
    namaDosen: "ASEP ZUHARA ARGAWINATA",
    namaDosenGelar: "",
    programStudi: "Sistem Informasi (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "01 Febriari 2021",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "Magister Ilmu Komunikasi",
    pendidikanS3: "Doktor",
  },
  {
    NIDN: "0401108606",
    NUPTK: "",
    namaDosen: "CARTI IRAWAN",
    namaDosenGelar: "",
    programStudi: "Sistem Informasi (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 April 2023",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Komputer",
    pendidikanS3: "",
  },
  {
    NIDN: "",
    NUPTK: 6038748649130213,
    namaDosen: "CECEP WARMAN",
    namaDosenGelar: "",
    programStudi: "Sistem Informasi (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "03 Mareti 2023",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "Magister Komputer",
    pendidikanS3: "",
  },
  {
    NIDN: "0405119501",
    NUPTK: "",
    namaDosen: "DEDE SUKMAWAN",
    namaDosenGelar: "",
    programStudi: "Sistem Informasi (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 April 2023",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Komputer",
    pendidikanS3: "",
  },
  {
    NIDN: "0410016703",
    NUPTK: "",
    namaDosen: "DENI HASMAN",
    namaDosenGelar: "",
    programStudi: "Sistem Informasi (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 November 2018",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Profesional",
    pendidikanS3: "Doktor Teknologi Pendidikan",
  },
  {
    NIDN: "0405088001",
    NUPTK: "",
    namaDosen: "DUDIH GUSTIAN",
    namaDosenGelar: "",
    programStudi: "Sistem Informasi (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 August 2019",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "",
    pendidikanS2: "Magister Ilmu Komputer",
    pendidikanS3: "",
  },
  {
    NIDN: "0408029102",
    NUPTK: "",
    namaDosen: "FALENTINO SEMBIRING",
    namaDosenGelar: "",
    programStudi: "Sistem Informasi (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 September 2022",
    Inpassing: "Penata Tk. I, golongan ruang III/d",
    tmtInpassing: "",
    pendidikanS2: "Magister Sistem Informasi",
    pendidikanS3: "",
    jabatan_struktural: "Ketua Prodi Sistem Informasi",
  },
  {
    NIDN: "0417087609",
    NUPTK: "",
    namaDosen: "GINA SYABANI YUDA",
    namaDosenGelar: "",
    programStudi: "Sistem Informasi (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "30 November 2020",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "Magister Pendidikan",
    pendidikanS3: "",
  },
  {
    NIDN: 8959920021,
    NUPTK: "",
    namaDosen: "GIRI VERIANTI",
    namaDosenGelar: "",
    programStudi: "Sistem Informasi (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 September 2022",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "",
    pendidikanS2: "Magister Pendidikan",
    pendidikanS3: "Doktor",
  },
  {
    NIDN: "0414069701",
    NUPTK: "",
    namaDosen: "HABI BATUROHMAH",
    namaDosenGelar: "",
    programStudi: "Sistem Informasi (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 October 2023",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Komputer",
    pendidikanS3: "",
  },
  {
    NIDN: "0418067208",
    NUPTK: "",
    namaDosen: "HENDRI EKASATRIA",
    namaDosenGelar: "",
    programStudi: "Sistem Informasi (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "01 November 2023",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "Magister Ilmu Kompter",
    pendidikanS3: "",
  },
  {
    NIDN: "0404069601",
    NUPTK: "",
    namaDosen: "M. ANTON PERMANA",
    namaDosenGelar: "",
    programStudi: "Sistem Informasi (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 April 2023",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Komputer",
    pendidikanS3: "",
  },
  {
    NIDN: "0429038601",
    NUPTK: "",
    namaDosen: "MUHAMAD MUSLIH",
    namaDosenGelar: "",
    programStudi: "Sistem Informasi (S1)",
    jabatanAkademik: "Lektor Kepala",
    tmtJad: "1 March 2024",
    Inpassing: "Pembina, golongan ruang IV/a",
    tmtInpassing: "",
    pendidikanS2: "Magister Ilmu Komputer",
    pendidikanS3: "",
  },
  {
    NIDN: "0414027906",
    NUPTK: "",
    namaDosen: "MUPAAT",
    namaDosenGelar: "",
    programStudi: "Sistem Informasi (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 January 2017",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Ilmu Komputer",
    pendidikanS3: "",
  },
  {
    NIDN: "0404128502",
    NUPTK: "",
    namaDosen: "NUNIK DESTRIA ARIANTI",
    namaDosenGelar: "",
    programStudi: "Sistem Informasi (S1)",
    jabatanAkademik: "Lektor Kepala",
    tmtJad: "1 December 2023",
    Inpassing: "Penata Tk. I, golongan ruang III/d",
    tmtInpassing: "",
    pendidikanS2: "Magister ilmu Komputer",
    pendidikanS3: "",
  },
  {
    NIDN: "0407058603",
    NUPTK: "",
    namaDosen: "RIESKA RAHAYU AYUNINGSIH",
    namaDosenGelar: "",
    programStudi: "Sistem Informasi (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 April 2024",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Komputer",
    pendidikanS3: "",
  },
  {
    NIDN: "0416098506",
    NUPTK: "",
    namaDosen: "SIHABUDIN",
    namaDosenGelar: "",
    programStudi: "Sistem Informasi (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 January 2023",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Ilmu Komputer",
    pendidikanS3: "",
  },
  {
    NIDN: "0414088608",
    NUPTK: "",
    namaDosen: "SUDIN SAEPUDIN",
    namaDosenGelar: "",
    programStudi: "Sistem Informasi (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 February 2021",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "",
    pendidikanS2: "Magister Komputer",
    pendidikanS3: "",
  },
  {
    NIDN: 8935420021,
    NUPTK: "",
    namaDosen: "SUMARNA",
    namaDosenGelar: "",
    programStudi: "Sistem Informasi (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "10 February 2021",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "Magister Pendidikan",
    pendidikanS3: "Doktor",
  },
  {
    NIDN: "0410058403",
    NUPTK: "",
    namaDosen: "WISUDA JATMIKO",
    namaDosenGelar: "",
    programStudi: "Sistem Informasi (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "13 December 2016",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "Magister Ilmu Komputer",
    pendidikanS3: "",
  },
  {
    NIDN: "0407098009",
    NUPTK: "",
    namaDosen: "ANANG SURYANA",
    namaDosenGelar: "",
    programStudi: "Teknik Elektro (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 December 2024",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Sains",
    pendidikanS3: "",
  },
  {
    NIDN: "0425068502",
    NUPTK: "",
    namaDosen: "ANGGY PRADIFTHA JUNFITHRANA",
    namaDosenGelar: "",
    programStudi: "Teknik Elektro (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 February 2021",
    Inpassing: "Penata Tk. I, golongan ruang III/d",
    tmtInpassing: "",
    pendidikanS2: "Magister Teknik",
    pendidikanS3: "",
  },
  {
    NIDN: "0402128905",
    NUPTK: "",
    namaDosen: "ARYO DE WIBOWO MUHAMMAD SIDIK",
    namaDosenGelar: "",
    programStudi: "Teknik Elektro (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 May 2023",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Teknik",
    pendidikanS3: "",
  },
  {
    NIDN: "",
    NUPTK: 3637762663130322,
    namaDosen: "ASEP DADAN HERMAWAN",
    namaDosenGelar: "",
    programStudi: "Teknik Elektro (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "14 September 2023",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "Magister Teknik Elektro",
    pendidikanS3: "",
  },
  {
    NIDN: "0403088504",
    NUPTK: "",
    namaDosen: "BAYU INDRAWAN",
    namaDosenGelar: "",
    programStudi: "Teknik Elektro (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 May 2024",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "",
    pendidikanS2: "Magister Teknik",
    pendidikanS3: "Doctor of Engineering",
  },
  {
    NIDN: "",
    NUPTK: 8735775676130202,
    namaDosen: "FIKRI ARIF WICAKSANA",
    namaDosenGelar: "",
    programStudi: "Teknik Elektro (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "07 August 2024",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "Magister Teknik",
    pendidikanS3: "",
  },
  {
    NIDN: 8965420021,
    NUPTK: "",
    namaDosen: "HANDREA BERNANDO TAMBUNAN",
    namaDosenGelar: "",
    programStudi: "Teknik Elektro (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 July 2022",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Master of Engineering",
    pendidikanS3: "",
  },
  {
    NIDN: "0115066804",
    NUPTK: "",
    namaDosen: "HARURIKSON LUMBANTOBING",
    namaDosenGelar: "",
    programStudi: "Teknik Elektro (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 May 2018",
    Inpassing: "Penata , golongan ruang III/c",
    tmtInpassing: "",
    pendidikanS2: "Magister kedokteran, Magister Kesehatan",
    pendidikanS3: "Doktor",
  },
  {
    NIDN: "0428119102",
    NUPTK: "",
    namaDosen: "ILMAN HIMAWAN KUSUMAH",
    namaDosenGelar: "",
    programStudi: "Teknik Elektro (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 October 2019",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Teknik",
    pendidikanS3: "",
  },
  {
    NIDN: "0403127308",
    NUPTK: "",
    namaDosen: "MARINA ARTIYASA",
    namaDosenGelar: "",
    programStudi: "Teknik Elektro (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 February 2021",
    Inpassing: "Penata , golongan ruang III/c",
    tmtInpassing: "",
    pendidikanS2: "Magister Teknik",
    pendidikanS3: "",
  },
  {
    NIDN: "0426019502",
    NUPTK: "",
    namaDosen: "MUCHTAR ALI SETYO YUDONO",
    namaDosenGelar: "",
    programStudi: "Teknik Elektro (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 October 2022",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Teknik",
    pendidikanS3: "",
  },
  {
    NIDN: "0427047803",
    NUPTK: "",
    namaDosen: "PANJI NARPUTRO",
    namaDosenGelar: "",
    programStudi: "Teknik Elektro (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "01 February 2024",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "Magister Teknik",
    pendidikanS3: "",
    jabatan_struktural: "Ketua Prodi Teknik Elektro",
  },
  {
    NIDN: "0425068002",
    NUPTK: "",
    namaDosen: "ODI AKHYARSI",
    namaDosenGelar: "",
    programStudi: "Teknik Mesin (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 Janurari 2024",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "",
    pendidikanS2: "Master of Engineering",
    pendidikanS3: "Doctor of Engineering",
  },
  {
    NIDN: "0306118401",
    NUPTK: "",
    namaDosen: "RINI KHAMIMATUL ULA",
    namaDosenGelar: "",
    programStudi: "Teknik Elektro (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 June 2024",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "",
    pendidikanS2: "Magister Sains",
    pendidikanS3: "Doktor Electrical Engineering",
  },
  {
    NIDN: "0420038701",
    NUPTK: "",
    namaDosen: "TRISIANI DEWI HENDRAWATI",
    namaDosenGelar: "",
    programStudi: "Teknik Elektro (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 March 2020",
    Inpassing: "Penata , golongan ruang III/c",
    tmtInpassing: "",
    pendidikanS2: "Magister Teknik Elektro",
    pendidikanS3: "",
  },
  {
    NIDN: "0428078801",
    NUPTK: "",
    namaDosen: "ADRIAN REZA",
    namaDosenGelar: "",
    programStudi: "Teknik Informatika (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 May 2016",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Teknik",
    pendidikanS3: "",
  },
  {
    NIDN: "0718108001",
    NUPTK: "",
    namaDosen: "ALUN SUJJADA",
    namaDosenGelar: "",
    programStudi: "Teknik Informatika (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 June 2024",
    Inpassing: "Penata , golongan ruang III/c",
    tmtInpassing: "",
    pendidikanS2: "Magister Teknik",
    pendidikanS3: "",
  },
  {
    NIDN: "0407029301",
    NUPTK: "",
    namaDosen: "ANGGUN FERGINA",
    namaDosenGelar: "",
    programStudi: "Teknik Informatika (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 December 2024",
    Inpassing: "Penata , golongan ruang III/c",
    tmtInpassing: "",
    pendidikanS2: "Magister Komputer",
    pendidikanS3: "",
  },
  {
    NIDN: "0416079801",
    NUPTK: "",
    namaDosen: "DHITA DIANA DEWI",
    namaDosenGelar: "",
    programStudi: "Teknik Informatika (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 June 2024",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "Magister Statitiska Terapan",
    pendidikanS3: "",
  },
  {
    NIDN: "0120220051",
    NUPTK: "",
    namaDosen: "DELISMAR",
    namaDosenGelar: "",
    programStudi: "Teknik Informatika (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "19 September 2022",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "Magister Pendidikan IPA",
    pendidikanS3: "Doktor - Pendidikan MIPA",
  },
  {
    NIDN: "0417077908",
    NUPTK: "",
    namaDosen: "GINA PURNAMA INSANY",
    namaDosenGelar: "",
    programStudi: "Teknik Informatika (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 June 2025",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Komputer",
    pendidikanS3: "",
  },
  {
    NIDN: "0402027401",
    NUPTK: "",
    namaDosen: "HERMANTO",
    namaDosenGelar: "",
    programStudi: "Teknik Informatika (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 April 2024",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Informatika",
    pendidikanS3: "",
  },
  {
    NIDN: "0427087802",
    NUPTK: "",
    namaDosen: "IMAM SANJAYA",
    namaDosenGelar: "",
    programStudi: "Teknik Informatika (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 March 2025",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Komputer",
    pendidikanS3: "",
  },
  {
    NIDN: "0409017604",
    NUPTK: "",
    namaDosen: "INDRA YUSTIANA",
    namaDosenGelar: "",
    programStudi: "Teknik Informatika (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 April 2019",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Informatika",
    pendidikanS3: "",
  },
  {
    NIDN: "0429038002",
    NUPTK: "",
    namaDosen: "IVANA LUCIA KHARISMA",
    namaDosenGelar: "",
    programStudi: "Teknik Informatika (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 March 2025",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Komputer",
    pendidikanS3: "",
  },
  {
    NIDN: 8955710021,
    NUPTK: "",
    namaDosen: "IWAN SETIAWAN",
    namaDosenGelar: "",
    programStudi: "Teknik Informatika (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "01 October 2020",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "Magister Teknik",
    pendidikanS3: "",
  },
  {
    NIDN: "0401107401",
    NUPTK: "",
    namaDosen: "KAMDAN",
    namaDosenGelar: "",
    programStudi: "Teknik Informatika (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 June 2025",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Komputer",
    pendidikanS3: "",
  },
  {
    NIDN: "0423049702",
    NUPTK: "",
    namaDosen: "LUSIANA SANI PARWATI",
    namaDosenGelar: "",
    programStudi: "Teknik Informatika (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 November 2024",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Matematika",
    pendidikanS3: "",
  },
  {
    NIDN: "0415049302",
    NUPTK: "",
    namaDosen: "MUHAMMAD IKHSAN THOHIR",
    namaDosenGelar: "",
    programStudi: "Teknik Informatika (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 July 2023",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Komputer",
    pendidikanS3: "",
  },
  {
    NIDN: "0413098904",
    NUPTK: "",
    namaDosen: "NUGRAHA",
    namaDosenGelar: "",
    programStudi: "Teknik Informatika (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "25 February 2025",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "Magister Komputer",
    pendidikanS3: "",
  },
  {
    NIDN: 8988560023,
    NUPTK: "",
    namaDosen: "NURKHAN",
    namaDosenGelar: "",
    programStudi: "Teknik Informatika (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "07 September 2022",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "Magister Agama",
    pendidikanS3: "Doctor Ilmu Pendidikan",
  },
  {
    NIDN: 8880001019,
    NUPTK: "",
    namaDosen: "NUZWAN SUDARIANA",
    namaDosenGelar: "",
    programStudi: "Teknik Informatika (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "10 February 2020",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "Magister Manajemen",
    pendidikanS3: "",
  },
  {
    NIDN: "0120220041",
    NUPTK: "",
    namaDosen: "RUMYATI",
    namaDosenGelar: "",
    programStudi: "Teknik Informatika (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "23 August 2022",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "Magister Teknologi Pendidikan",
    pendidikanS3: "Doktor Penelitian dan Evaluasi Pendidikan",
  },
  {
    NIDN: 8941530021,
    NUPTK: "",
    namaDosen: "SETIAWATI",
    namaDosenGelar: "",
    programStudi: "Teknik Informatika (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 May 2022",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "",
    pendidikanS2: "Magister Pendidikan",
    pendidikanS3: "Doktor Ilmu Pendidikan",
  },
  {
    NIDN: "0419128801",
    NUPTK: "",
    namaDosen: "SOMANTRI",
    namaDosenGelar: "",
    programStudi: "Teknik Informatika (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 January 2023",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "",
    pendidikanS2: "Magister Informatika",
    pendidikanS3: "",
    jabatan_struktural: "Ketua Prodi Teknik Informatika",
  },
  {
    NIDN: 8875823420,
    NUPTK: "",
    namaDosen: "SUPRAPTO",
    namaDosenGelar: "",
    programStudi: "Teknik Informatika (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad:
      "###############################################################################################################################################################################################################################################################",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "Magister Manajemen",
    pendidikanS3: "Doktor Ilmu Pendidikan",
  },
  {
    NIDN: 8888290019,
    NUPTK: "",
    namaDosen: "YURMAN ZAINAL",
    namaDosenGelar: "",
    programStudi: "Teknik Informatika (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "1 August 2018",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "Magister Manajemen",
    pendidikanS3: "Doktor - Ilmu Pendidikan",
  },
  {
    NIDN: "0409069602",
    NUPTK: "",
    namaDosen: "ZAENAL ALAMSYAH",
    namaDosenGelar: "",
    programStudi: "Teknik Informatika (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 April 2023",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Komputer",
    pendidikanS3: "",
  },
  {
    NIDN: "0410107806",
    NUPTK: "",
    namaDosen: "ZELDI SURYADY",
    namaDosenGelar: "",
    programStudi: "Teknik Informatika (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "20 March 2016",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "Master of Science",
    pendidikanS3: "Doktor Komputer science",
  },
  {
    NIDN: "0120240040",
    NUPTK: "",
    namaDosen: "ABD RAHMAN BIN ABDUL RAHIM",
    namaDosenGelar: "",
    programStudi: "Teknik Mesin (S1)",
    jabatanAkademik: "Lektor Kepala",
    tmtJad: "26 February 2007",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "Master of Science",
    pendidikanS3: "Doctor Of Pholosophy",
  },
  {
    NIDN: "0428118903",
    NUPTK: "",
    namaDosen: "AGUSTAMI SITORUS",
    namaDosenGelar: "",
    programStudi: "Teknik Mesin (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 August 2018",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Master of Science",
    pendidikanS3: "",
  },
  {
    NIDN: "0417118205",
    NUPTK: "",
    namaDosen: "ANDI RINALDI HASAN",
    namaDosenGelar: "",
    programStudi: "Teknik Mesin (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 May 2017",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "",
    pendidikanS3: "",
  },
  {
    NIDN: "0424038703",
    NUPTK: "",
    namaDosen: "ARIES KARYADI",
    namaDosenGelar: "",
    programStudi: "Teknik Mesin (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 August 2018",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "",
    pendidikanS3: "",
  },
  {
    NIDN: "0325127607",
    NUPTK: "",
    namaDosen: "CHRIS SALIM",
    namaDosenGelar: "",
    programStudi: "Teknik Mesin (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "02 August 2021",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "Master of Engineering",
    pendidikanS3: "Doctor of Engineering",
  },
  {
    NIDN: "0429038703",
    NUPTK: "",
    namaDosen: "DANI MARDIYANA",
    namaDosenGelar: "",
    programStudi: "Teknik Mesin (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 December 2024",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "",
    pendidikanS2: "Magister Teknik",
    pendidikanS3: "",
  },
  {
    NIDN: "0423119002",
    NUPTK: "",
    namaDosen: "DODI IWAN SUMARNO",
    namaDosenGelar: "",
    programStudi: "Teknik Mesin (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 March 2021",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Teknik",
    pendidikanS3: "",
  },
  {
    NIDN: "0424089501",
    NUPTK: "",
    namaDosen: "DWI MARDIKA LESTARI",
    namaDosenGelar: "",
    programStudi: "Teknik Mesin (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "Master of Science",
    pendidikanS3: "",
  },
  {
    NIDN: "0406029002",
    NUPTK: "",
    namaDosen: "FABROBI FAZLUR RIDHA",
    namaDosenGelar: "",
    programStudi: "Teknik Mesin (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 January 2023",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Teknik",
    pendidikanS3: "",
  },
  {
    NIDN: "0422098102",
    NUPTK: "",
    namaDosen: "HEPPI FAMILIANA",
    namaDosenGelar: "",
    programStudi: "Teknik Mesin (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 August 2018",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Teknik",
    pendidikanS3: "",
  },
  {
    NIDN: "0415039402",
    NUPTK: "",
    namaDosen: "LAZUARDI AKMAL ISLAMI",
    namaDosenGelar: "",
    programStudi: "Teknik Mesin (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 June 2025",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Sains",
    pendidikanS3: "",
    jabatan_struktural: "Ketua Prodi Teknik Mesin",
  },
  {
    NIDN: "0418028708",
    NUPTK: "",
    namaDosen: "MOCHAMMAD ARVIN SYARIFUDDIN",
    namaDosenGelar: "",
    programStudi: "Teknik Mesin (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 June 2021",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Teknik",
    pendidikanS3: "",
  },
  {
    NIDN: 8809290019,
    NUPTK: "",
    namaDosen: "MULYADI",
    namaDosenGelar: "",
    programStudi: "Teknik Mesin (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 June 2019",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Teknik",
    pendidikanS3: "",
  },
  {
    NIDN: "0120240039",
    NUPTK: "",
    namaDosen: "SIVAKUMAR NALAPPAN SELLAPPAN",
    namaDosenGelar: "",
    programStudi: "Teknik Mesin (S1)",
    jabatanAkademik: "Lektor Kepala",
    tmtJad: "",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "Master Of Engineering",
    pendidikanS3: "Doktor of Philosophy",
  },
  {
    NIDN: 9904020037,
    NUPTK: "",
    namaDosen: "SRIYONO",
    namaDosenGelar: "",
    programStudi: "Teknik Mesin (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "1 August 2016",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "Magister Teknik",
    pendidikanS3: "",
  },
  {
    NIDN: "0410109701",
    NUPTK: "",
    namaDosen: "ZAID SULAIMAN",
    namaDosenGelar: "",
    programStudi: "Teknik Mesin (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 March 2025",
    Inpassing: "Penata golongan ruang III/c",
    tmtInpassing: "",
    pendidikanS2: "Magister Teknik",
    pendidikanS3: "",
  },
  {
    NIDN: "0410059401",
    NUPTK: "",
    namaDosen: "ARDIN ROZANDI",
    namaDosenGelar: "",
    programStudi: "Teknik Sipil (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 April 2023",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Teknik",
    pendidikanS3: "",
  },
  {
    NIDN: "0405036803",
    NUPTK: "",
    namaDosen: "ANDRIJANTO",
    namaDosenGelar: "",
    programStudi: "Teknik Sipil (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "",
    pendidikanS3: "",
  },
  {
    NIDN: 8963060022,
    NUPTK: "",
    namaDosen: "AKHMAD ZAENAL ABIDIN",
    namaDosenGelar: "",
    programStudi: "Teknik Sipil (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "Magister Pendidikan",
    pendidikanS3: "Doktor Teknologi Pendidikan",
  },
  {
    NIDN: 8875580018,
    NUPTK: "",
    namaDosen: "BAMBANG JATMIKA",
    namaDosenGelar: "",
    programStudi: "Teknik Sipil (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 February 2021",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Teknik",
    pendidikanS3: "",
  },
  {
    NIDN: 8866501019,
    NUPTK: "",
    namaDosen: "CECE SUHENDI",
    namaDosenGelar: "",
    programStudi: "Teknik Sipil (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 March 2021",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Teknik",
    pendidikanS3: "",
  },
  {
    NIDN: "0416038503",
    NUPTK: "",
    namaDosen: "DANIEL ARIE SUSANTO",
    namaDosenGelar: "",
    programStudi: "Teknik Sipil (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 September 2022",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Teknik",
    pendidikanS3: "",
  },
  {
    NIDN: "0412099205",
    NUPTK: "",
    namaDosen: "DANANG PURWANTO",
    namaDosenGelar: "",
    programStudi: "Teknik Sipil (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "14 February 2022",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "Master Of Engineering",
    pendidikanS3: "",
  },
  {
    NIDN: "0404069001",
    NUPTK: "",
    namaDosen: "DEBBY RAHMAWATI, S.T.,M.T",
    namaDosenGelar: "",
    programStudi: "Teknik Sipil (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 January 2017",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b;",
    tmtInpassing: "",
    pendidikanS2: "",
    pendidikanS3: "",
  },
  {
    NIDN: "0413128903",
    NUPTK: "",
    namaDosen: "DEWI SARTIKA",
    namaDosenGelar: "",
    programStudi: "Teknik Sipil (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 August 2018",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b;",
    tmtInpassing: "",
    pendidikanS2: "",
    pendidikanS3: "",
  },
  {
    NIDN: "0416039303",
    NUPTK: "",
    namaDosen: "DIO DAMAS PERMADI",
    namaDosenGelar: "",
    programStudi: "Teknik Sipil (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 April 2024",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b;",
    tmtInpassing: "",
    pendidikanS2: "Master of Engineering",
    pendidikanS3: "",
  },
  {
    NIDN: 8932060022,
    NUPTK: "",
    namaDosen: "FURTASIH",
    namaDosenGelar: "",
    programStudi: "Teknik Sipil (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "23 August 2021",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "Magister Pendidkan",
    pendidikanS3: "Doktor Teknologi Pendidikan",
  },
  {
    NIDN: 8900060022,
    NUPTK: "",
    namaDosen: "ENENG RAHMI",
    namaDosenGelar: "",
    programStudi: "Teknik Sipil (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "24 July 2023",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "s",
    pendidikanS3: "Doktor Ilmu Lingkungan",
  },
  {
    NIDN: "0408088901",
    NUPTK: "",
    namaDosen: "HASAN BASRI MAULANA, S.T.,M.T",
    namaDosenGelar: "",
    programStudi: "Teknik Sipil (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 January 2017",
    Inpassing: "Penata Muda Tk. I, Golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "",
    pendidikanS3: "",
  },
  {
    NIDN: 8942060022,
    NUPTK: "",
    namaDosen: "HUJAIR FAIZAN",
    namaDosenGelar: "",
    programStudi: "Teknik Sipil (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "23 August 2021",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "Magister Pendidikan",
    pendidikanS3: "Doktor Teknologi Pendidikan",
  },
  {
    NIDN: 8890070018,
    NUPTK: "",
    namaDosen: "JASMANSYAH",
    namaDosenGelar: "",
    programStudi: "Teknik Sipil (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 April 2019",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "Magister Pendidikan",
    pendidikanS3: "Doktor Pendidikan",
  },
  {
    NIDN: "0429099603",
    NUPTK: "",
    namaDosen: "LIOBA EVITA ANIKUSUMA",
    namaDosenGelar: "",
    programStudi: "Teknik Sipil (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 June 2025",
    Inpassing: "Penata Muda Tk. I, Golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Teknik",
    pendidikanS3: "",
  },
  {
    NIDN: 892006002,
    NUPTK: "",
    namaDosen: "MARJUKI",
    namaDosenGelar: "",
    programStudi: "Teknik Sipil (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "Magister Manajemen Pendidikan",
    pendidikanS3: "Doktor Pendidikan",
  },
  {
    NIDN: "0423049001",
    NUPTK: "",
    namaDosen: "MUHAMMAD AMMAR",
    namaDosenGelar: "",
    programStudi: "Teknik Sipil (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 January 2017",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "",
    pendidikanS3: "",
  },
  {
    NIDN: "0414119701",
    NUPTK: "",
    namaDosen: "MUHAMMAD HIDAYAT",
    namaDosenGelar: "",
    programStudi: "Teknik Sipil (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 June 2023",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Master of Engineering",
    pendidikanS3: "",
  },
  {
    NIDN: "0120240016",
    NUPTK: "",
    namaDosen: "MUHAMMAD SUBANDI",
    namaDosenGelar: "",
    programStudi: "Teknik Sipil (S1)",
    jabatanAkademik: "Profesor",
    tmtJad: "",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "Magister Pertanian",
    pendidikanS3: "Doktor Ilmu Pertanian",
  },
  {
    NIDN: "0420119702",
    NUPTK: "",
    namaDosen: "NADHYA SUSILO NUGROHO",
    namaDosenGelar: "Nadhya Susilo Nugroho, S.T., M.T.",
    programStudi: "Teknik Sipil (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "01 September 2023",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "Magister Teknik",
    pendidikanS3: "",
  },
  {
    NIDN: "0403029301",
    NUPTK: "",
    namaDosen: "NITA KURNITA SARI",
    namaDosenGelar: "",
    programStudi: "Teknik Sipil (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "18 September 2023",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "Master of Engineering",
    pendidikanS3: "",
  },
  {
    NIDN: "0402037401",
    NUPTK: "",
    namaDosen: "PAIKUN",
    namaDosenGelar: "",
    programStudi: "Teknik Sipil (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 August 2023",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "",
    pendidikanS2: "Magister Teknik",
    pendidikanS3: "",
  },
  {
    NIDN: "0413098004",
    NUPTK: "",
    namaDosen: "RICHA RAHMALIYA SUNHADJI",
    namaDosenGelar: "",
    programStudi: "Teknik Sipil (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 June 2023",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "Magister Teknik",
    pendidikanS3: "",
  },
  {
    NIDN: "0418099001",
    NUPTK: "",
    namaDosen: "RICO SIHOTANG, S.T.,M.T",
    namaDosenGelar: "",
    programStudi: "Teknik Sipil (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 January 2017",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "",
    pendidikanS3: "",
  },
  {
    NIDN: "0402109401",
    NUPTK: "",
    namaDosen: "SELFIN ANUGRAH AMDANI",
    namaDosenGelar: "",
    programStudi: "Teknik Sipil (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 April 2023",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "Magister Teknik",
    pendidikanS3: "",
  },
  {
    NIDN: "0422048703",
    NUPTK: "",
    namaDosen: "TRIONO",
    namaDosenGelar: "",
    programStudi: "Teknik Sipil (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 January 2023",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "",
    pendidikanS3: "",
  },
  {
    NIDN: "0422108804",
    NUPTK: "",
    namaDosen: "UTAMY SUKMAYU SAPUTRI",
    namaDosenGelar: "",
    programStudi: "Teknik Sipil (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 January 2024",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "",
    pendidikanS2: "Magister Teknik",
    pendidikanS3: "",
    jabatan_struktural: "Ketua Prodi Teknik Sipil",
  },
  {
    NIDN: "012025013",
    NUPTK: "",
    namaDosen: "WILLIAMS DUNU",
    namaDosenGelar: "",
    programStudi: "Teknik Sipil (S1)",
    jabatanAkademik: "Lektor Kepala",
    tmtJad: "9 January 2025",
    Inpassing: "",
    tmtInpassing: "",
    pendidikanS2: "Master Of Science Constructor Technology",
    pendidikanS3: "Doctor Of Philosophy",
  },
];
