export const dataDosen = [
  {
    NIDN: "0410066303",
    NUPTK: "5942741642130122",
    namaDosen: "ANDY YUNIARSO",
    namaDosenGelar: "Andy Yuniarso, SE., MM., MBA.",
    programStudi: "Akuntansi (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "05 Februari 2018",
    pendidikanS2: "Magister Manajemen",
  },
  {
    NIDN: "0422059502",
    NUPTK: "2854773674230242",
    namaDosen: "DANIA MEIDA ROSYIDAH",
    namaDosenGelar: "Dania Meida Rosyidah, S.Ak., M.Ak.",
    programStudi: "Akuntansi (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 Januari 2024",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 Mei 2024",
    pendidikanS2: "Magister Akuntansi",
  },
  {
    NIDN: "1515129301",
    NUPTK: "4547771672230313",
    namaDosen: "DEA ARME TIARA HARAHAP",
    namaDosenGelar: "Dea Arme Tiara Harahap, S.Ak., M.Ak.",
    programStudi: "Akuntansi (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "02 Mei 2024",
    pendidikanS2: "Magister Akuntansi",
  },
  {
    NIDN: "0416066602",
    NUPTK: "2948744645230142",
    namaDosen: "ELIN PAULINA",
    namaDosenGelar: "Dra. Elin Paulina, M.M.",
    programStudi: "Akuntansi (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 April 2023",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 September 2023",
    pendidikanS2: "Magister Manajemen",
  },
  {
    NIDN: "0419118903\t",
    NUPTK: "1451767668230243",
    namaDosen: "HELIANI",
    namaDosenGelar: "Heliani, S.E., M.Ak.",
    programStudi: "Akuntansi (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 September 2022",
    Inpassing: "Penata Tk. I, golongan ruang III/d",
    tmtInpassing: "01 Januari 2026",
    pendidikanS2: "Magister Akuntansi",
    jabatan_struktural: "Ketua Prodi Akuntansi",
  },
  {
    NIDN: "\t0428047904",
    NUPTK: "8760757658130132",
    namaDosen: "IRWAN HERMAWAN",
    namaDosenGelar: "Irwan Hermawan, S.E., M.E.",
    programStudi: "Akuntansi (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 Oktober 2019",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 Maret 2020",
    pendidikanS2: "Magister Ekonomi",
  },
  {
    NIDN: "0425119401\t",
    NUPTK: "9457772673230253",
    namaDosen: "MEUTIA RIANY",
    namaDosenGelar: "Meutia Riany, S.E., M.Ak.",
    programStudi: "Akuntansi (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 Juni 2023",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 November 2023",
    pendidikanS2: "Magister Akuntansi",
  },
  {
    NIDN: "0412079302",
    NUPTK: "3044771672130373",
    namaDosen: "MUHAMMAD ZULVAN DWI HATMOKO",
    namaDosenGelar: "Muhammad Zulvan Dwi Hatmoko, S.E., M.Acc.",
    programStudi: "Akuntansi (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 April 2024",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 September 2024",
    pendidikanS2: "Magister Akuntansi",
  },
  {
    NIDN: "8992810021\t",
    NUPTK: "9450760661130172",
    namaDosen: "MULUS WIJAYA KUSUMA",
    namaDosenGelar: "Mulus Wiajaya Kusuma, S.E., M.Ec.Dev., Ph.D.",
    programStudi: "Akuntansi (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 Agustus 2022",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "01 Januari 2023",
    pendidikanS2: "Magister Ekonomi",
  },
  {
    NIDN: "0410128303",
    NUPTK: "1542761662130263",
    namaDosen: "NANAN SUNANDAR",
    namaDosenGelar: "Nanan Sunandar, S.E., M.Akt.",
    programStudi: "Akuntansi (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 Maret 2023",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 Juni 2020",
    pendidikanS2: "Magister Akuntansi",
  },
  {
    NIDN: "0428069601\t",
    NUPTK: "2960774675230222",
    namaDosen: "NUR HIDAYAH KUSUMANINGRUM FADHILAH",
    namaDosenGelar: "Nur Hidayah Kusumaningrum Fadhillah, S.E., M.Ak.",
    programStudi: "Akuntansi (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 Desember 2024",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "01 Januari 2026",
    pendidikanS2: "Magister Akuntansi",
  },
  {
    NIDN: "\t0403089501\t",
    NUPTK: "2135773674130253",
    namaDosen: "NURUL RUSDIANSYAH",
    namaDosenGelar: "Nurul Rusdiansyah, S.Akun., M.Ak.",
    programStudi: "Akuntansi (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 November 2023",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 Januari 2024",
    pendidikanS2: "Magister Akuntansi",
  },
  {
    NIDN: "0421109402\t",
    NUPTK: "9353772673130213",
    namaDosen: "TAOFIK MUHAMMAD GUMELAR",
    namaDosenGelar: "Taofik Muhammad Gumelar, S.E., M.Ak.",
    programStudi: "Akuntansi (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 Juni 2025",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "01 Januari 2026",
    pendidikanS2: "Magister Akuntansi",
  },
  {
    NIDN: "0120240046",
    namaDosen: "ANGEL ESMERALDA",
    namaDosenGelar: "Dr. Angel II Pornasdoro Esmeralda",
    programStudi: "Akuntansi (S1)",
    jabatanAkademik: "Lektor Kepala",
    tmtJad: "18 Oktober 2024",
    pendidikanS2: "Magister - Manajemen Bisnis",
    pendidikanS3: "Doktor - Manajemen Bisnis",
  },
  {
    NIDN: "0407128602",
    NUPTK: "0539764665231103",
    namaDosen: "AAN SETIAWATI",
    namaDosenGelar: "Aan Setiawati, S.Pd., M.Ds.",
    programStudi: "Desain Komunikasi Visual (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "1 January 2017",
    Inpassing: "Penata Muda Tk. I, Golongan Ruang III/b",
    tmtInpassing: "01 Maret 2017",
    pendidikanS2: "Magister Desain",
  },
  {
    NIDN: "0431088506",
    NUPTK: "0163763664130173",
    namaDosen: "AGUS DARMAWAN",
    namaDosenGelar: "Agus Darmawan, S.Sn., M.Sn.",
    programStudi: "Desain Komunikasi Visual (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 Desember 2024",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "01 Januari 2026",
    pendidikanS2: "Magister Seni",
    jabatan_struktural: "Ketua Prodi Desain Komunikasi Visual",
  },
  {
    NIDN: "8951550022\t",
    NUPTK: "6939764665200002",
    namaDosen: "ASEP SUTISNA SANJAYA",
    namaDosenGelar: "Dr. Asep Sutisna Sanjaya, M.Pd.",
    programStudi: "Desain Komunikasi Visual (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "06 Juli 2021",
    pendidikanS2: "Magister Pendidikan",
    pendidikanS3: "Doktor - Penelitian dan Evaluasi Pendidikan",
  },
  {
    NIDN: "\t0409077901\t",
    NUPTK: "7041757659200033",
    namaDosen: "ASEP WAHYUDIN",
    namaDosenGelar: "Asep Wahyudin , S.Sn. M.Sn.",
    programStudi: "Desain Komunikasi Visual (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 Mei 2016",
    Inpassing: "Penata Muda Tk. I, Golongan Ruang III/b",
    tmtInpassing: "01 September 2016",
    pendidikanS2: "Magister Seni",
  },
  {
    NIDN: "8961550022",
    NUPTK: "2558742643200013",
    namaDosen: "BUDI SETIADI",
    namaDosenGelar: "Dr. Budi Setiadi, M.Pd.",
    programStudi: "Desain Komunikasi Visual (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    pendidikanS2: "Magister Pendidikan",
    pendidikanS3: "Doktor Administrasi Pendidikan",
  },
  {
    NIDN: "0405029503",
    NUPTK: "0537773674130242",
    namaDosen: "FIRMAN MUTAQIN",
    namaDosenGelar: "Firman Mutaqin, S.Ds., M.Ds.",
    programStudi: "Desain Komunikasi Visual (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 November 2024",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 April 2025",
    pendidikanS2: "Magister Desain",
  },
  {
    NIDN: "0408068805",
    NUPTK: "6940766667220012",
    namaDosen: "GESNIDA YUNITA",
    namaDosenGelar: "Gesnida Yunita, S.Sn., M.Sn.",
    programStudi: "Desain Komunikasi Visual (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 Maret 2023",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b;",
    tmtInpassing: "01 Mei 2023",
    pendidikanS2: "Magister Seni",
  },
  {
    NIDN: "8910060022",
    NUPTK: "5052755658200003",
    namaDosen: "HERWAN",
    namaDosenGelar: "Dr. Herwan, S.Pd.I., M.M.Pd.",
    programStudi: "Desain Komunikasi Visual (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "25 Juni 2021",
    pendidikanS2: "Magister Manajemen Pendidikan",
    pendidikanS3: "Doktor Pendidikan Islam",
  },
  {
    NIDN: "0409107907",
    NUPTK: "1242757659300063",
    namaDosen: "ICUH KOMALA",
    namaDosenGelar: "Icuh Komala, S.Sn., M.Sn.",
    programStudi: "Desain Komunikasi Visual (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 Oktober 2019",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 Maret 2020",
    pendidikanS2: "Magister Seni",
  },
  {
    NIDN: "9990518873",
    NUPTK: "5748762663231082",
    namaDosen: "IRNI RESMI APRIYANTI",
    namaDosenGelar: "Irni Resmi Apriyanti, S.Ds., M.Ds.",
    programStudi: "Desain Komunikasi Visual (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "01 Agustus 2024",
    pendidikanS2: "Magister Desain",
  },
  {
    NIDN: "3542776677130052",
    NUPTK: "3542776677130052",
    namaDosen: "IRVING GUSTAV SALIM, S.PD.",
    namaDosenGelar: "Irving Gustav Salim, S.Pd., M.Ds.",
    programStudi: "Desain Komunikasi Visual (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "01 Agustus 2024",
    pendidikanS2: "Magister Desain",
  },
  {
    NIDN: "0408108704",
    NUPTK: "2440765666130263",
    namaDosen: "MOCHAMAD FICKY AULIA",
    namaDosenGelar: "Mochamad Ficky Aulia, S.Ds., M.Sn.",
    programStudi: "Desain Komunikasi Visual (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 Juni 2024",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "01 Januari 2026",
    pendidikanS2: "Magister Seni",
  },
  {
    NIDN: "0419128603",
    namaDosen: "PRAWIRA YUDHA MAPPALAHERE",
    namaDosenGelar: "Prawira Yudha Mappalahere, S.T., M.Ds.",
    programStudi: "Desain Komunikasi Visual (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 Januari 2017",
    Inpassing: "Penata Muda Tk. I Golongan III/b",
    tmtInpassing: "01 Maret 2017",
    pendidikanS2: "Magister Desain",
  },
  {
    NIDN: "0422079203",
    NUPTK: "4054770671230313",
    namaDosen: "RARAY ISTIANAH",
    namaDosenGelar: "Raray Istianah S.Pd., M.Pd.",
    programStudi: "Desain Komunikasi Visual (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 Agustus 2025",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "01 Januari 2026",
    pendidikanS2: "Magister Pendidikan",
  },
  {
    NIDN: "0416019501",
    NUPTK: "2448773674130202",
    namaDosen: "RIFKY NUGRAHA",
    namaDosenGelar: "Rifky Nugraha, S.Pd., M.Ds.",
    programStudi: "Desain Komunikasi Visual (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 November 2024",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 April 2025",
    pendidikanS2: "Magister Desain",
  },
  {
    NIDN: "0430109501",
    NUPTK: "7362773674130233",
    namaDosen: "TULUS REGA WAHYUNI E",
    namaDosenGelar: "Tulus Rega Wahyuni E, S.Kom.I., M.Sn.",
    programStudi: "Desain Komunikasi Visual (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 Agustus 2025",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "01 Januari 2026",
    pendidikanS2: "Magister Seni",
  },
  {
    NIDN: "8971550022",
    NUPTK: "6445751652300022",
    namaDosen: "WATI SOLIHAT SUKMAWATI",
    namaDosenGelar: "Dr. Wati Solihat Sukmawati., S.S., M.M.Pd.",
    programStudi: "Desain Komunikasi Visual (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "07 Juli 2021",
    pendidikanS2: "Magister Manajemen Pendidikan",
    pendidikanS3: "Doktor Sastra",
  },
  {
    NIDN: "0426069302",
    NUPTK: "7958771672130342",
    namaDosen: "ARMANSYAH",
    namaDosenGelar: "Armansyah, S.H., M.H.",
    programStudi: "Hukum (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 November 2023",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 April 2024",
    pendidikanS2: "Magister Hukum",
  },
  {
    NIDN: "0414058705",
    NUPTK: "0846765666131172",
    namaDosen: "CEP SAEPUL ALAM TEDDY LESMANA",
    namaDosenGelar: "Cep Saepul Alam Teddy Lesmana, S.H., M.H.",
    programStudi: "Hukum (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 Desember 2022",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "01 Januari 2024",
    pendidikanS2: "Magister Hukum",
  },
  {
    NIDN: "0424019501",
    NUPTK: "6456773674230222",
    namaDosen: "ENDAH PERTIWI",
    namaDosenGelar: "Endah Pertiwi, S.H., M.Kn.",
    programStudi: "Hukum (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 Juli 2023",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "01 Januari 2026",
    pendidikanS2: "Magister Kenotariatan",
    jabatan_struktural: "Ketua Prodi Hukum",
  },
  {
    NIDN: "0411068302",
    NUPTK: "5943761662130222",
    namaDosen: "FERDY FERDIAN",
    namaDosenGelar: "Ferdy Ferdian, S.H.",
    programStudi: "Hukum (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "19 Februari 2010",
    pendidikanS2: "Magister Ilmu Hukum",
  },
  {
    NIDN: "8986580023",
    namaDosen: "HAPPY DAVID PRADHAN",
    programStudi: "Hukum (S1)",
    jabatanAkademik: "Lektor Kepala",
    tmtJad: "01 Juli 2023",
    pendidikanS2: "Magister hukum bisnis",
    pendidikanS3: "Doktor Ilmu Hukum",
  },
  {
    NIDN: "0407016701",
    NUPTK: "7439745646130102",
    namaDosen: "HERI HERIYANTO",
    namaDosenGelar: "Dr. dr. Heri Heriyanto, M.M.",
    programStudi: "Hukum (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 Mei 2024",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "01 April 2025",
    pendidikanS2: "Magister Manajemen",
    pendidikanS3: "Doktor Ilmu Hukum",
  },
  {
    NIDN: "0403126302",
    NUPTK: "1535741642130093",
    namaDosen: "JUNAIDI",
    namaDosenGelar: "Drs. Junaidi, M.M.",
    programStudi: "Hukum (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "01 Februari 2018",
  },
  {
    NIDN: "0120240047",
    namaDosen: "MARCO MARCHETTI",
    programStudi: "Hukum (S1)",
    jabatanAkademik: "Profesor",
    pendidikanS2: "Magister",
    pendidikanS3: "Doktor Ilmu Hukum",
  },
  {
    NIDN: "0417019305",
    NUPTK: "4449771672130262",
    namaDosen: "MUHAMAD RIZKI ABDUL MALIK",
    namaDosenGelar: "Muhamad Rizki Abdul Malik, S.H., M.H",
    programStudi: "Hukum (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 Juni 2025",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 Juli 2025",
    pendidikanS2: "Magister Hukum",
  },
  {
    NIDN: "0429129602",
    NUPTK: "1561774675130173",
    namaDosen: "MUHAMMAD RIDHO SINAGA",
    namaDosenGelar: "Muhammad Ridho Sinaga, S.H., M.H.",
    programStudi: "Hukum (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 Juli 2025",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "01 Januari 2026",
    pendidikanS2: "Magister Hukum",
  },
  {
    NIDN: "0402048801",
    NUPTK: "7734766667130322",
    namaDosen: "NUCHRAHA ALHUDA HASNDA",
    namaDosenGelar: "Nuchraha Alhuda Hasnda, S.H., M.H.",
    programStudi: "Hukum (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 Juni 2025",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "01 Januari 2026",
    pendidikanS2: "Magister Hukum",
  },
  {
    NIDN: "0415098002",
    NUPTK: "8247758659230213",
    namaDosen: "RIDA ISTA SITEPU",
    namaDosenGelar: "Rida Ista Br Sitepu, S.H., M.H.",
    programStudi: "Hukum (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 Oktober 2022",
    Inpassing: "Penata Tk. I, golongan ruang III/d",
    tmtInpassing: "01 Januari 2026",
    pendidikanS2: "Magister Hukum",
  },
  {
    NIDN: "0120240064",
    namaDosen: "SARITA NANDMEHAR,",
    programStudi: "Hukum (S1)",
    jabatanAkademik: "Lektor Kepala",
    pendidikanS2: "Magister Hukum",
    pendidikanS3: "Doktor Ilmu Hukum",
  },
  {
    NIDN: "8988700020",
    NUPTK: "4835740641130092",
    namaDosen: "SUMARTA SETIADI",
    namaDosenGelar: "Sumarta Setiadi, S.H., M.H.",
    programStudi: "Hukum (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "01 Juli 2020",
    pendidikanS2: "Magister Hukum",
  },
  {
    NIDN: "0420129103",
    NUPTK: "5552769670130283",
    namaDosen: "UJANG BADRU JAMAN",
    namaDosenGelar: "Ujang Badru Jaman, S.H., M.H.",
    programStudi: "Hukum (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 Desember 2024",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "01 Januari 2026",
    pendidikanS2: "Magister Hukum",
  },
  {
    NIDN: "0409046201",
    NUPTK: "8741740641130072",
    namaDosen: "ZAENAL ABIDIN",
    namaDosenGelar: "Zaenal Abidin, S.H., M.H.",
    programStudi: "Hukum (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "04 Februari 2019",
    pendidikanS2: "Magister Hukum",
  },
  {
    NIDN: "0420057201",
    NUPTK: "0846765666131172",
    namaDosen: "BRAM BACHRUM BAAN",
    programStudi: "Hukum (S2)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 Mei 2024",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "01 Maret 2025",
    pendidikanS2: "Magister Hukum",
    pendidikanS3: "Doktor Ilmu hukum",
  },
  {
    NIDN: "0417038708",
    NUPTK: "3649765666131092",
    namaDosen: "M. ROKEN FADLY. MK",
    namaDosenGelar: "M. Roken Fadly. MK., S.H., M.H.",
    programStudi: "Hukum (S2)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "01 September 2022",
    pendidikanS2: "Magister Hukum",
    pendidikanS3: "Doktor Ilmu Hukum",
  },
  {
    NIDN: "0401067608",
    NUPTK: "5933754655130132",
    namaDosen: "PADLILAH",
    namaDosenGelar: "Dr. Padlilah, S.H., M.H.",
    programStudi: "Hukum (S2)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 Mei 2024",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "01 Maret 2025",
    pendidikanS2: "Magister Hukum",
    pendidikanS3: "Doktor Ilmu Hukum",
  },
  {
    NIDN: "0413066805",
    NUPTK: "5945746647130102",
    namaDosen: "RAHMATSYAH",
    namaDosenGelar: "Dr. Rahmatsyah, S.H., M.M., M.H.",
    programStudi: "Hukum (S2)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 Juli 2023",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "01 Januari 2024",
    pendidikanS2: "Magister Hukum",
    pendidikanS3: "Doktor Ilmu Hukum",
  },
  {
    NIDN: "0405058002",
    NUPTK: "8837758659232122",
    namaDosen: "RR. DEWI ANGGRAENI",
    namaDosenGelar: "Dr. Dewi Anggraeni, S.H., M.H.",
    programStudi: "Hukum (S2)",
    jabatanAkademik: "Profesor",
    tmtJad: "01 November 2023",
    Inpassing: "Pembina, golongan ruang IV/a",
    tmtInpassing: "01 Januari 2024",
    pendidikanS2: "Magister Hukum",
    pendidikanS3: "Doktor Ilmu Hukum",
  },
  {
    NIDN: "0206077202",
    NUPTK: "5038750651130193",
    namaDosen: "DEDEN WITARSYAH",
    namaDosenGelar: "Deden Witarsyah, S.T., M.Eng., Ph.D.",
    programStudi: "Ilmu Komputer (S3)",
    jabatanAkademik: "Lektor Kepala",
    tmtJad: "01 Juni 2023",
    Inpassing: "Pembina, golongan ruang IV/a",
    tmtInpassing: "01 Januari 2026",
    pendidikanS2: "Master of Engineering Science Electrical Engineering",
    pendidikanS3: "Doctor Of Pilosophy",
  },
  {
    NIDN: "0406097702",
    NUPTK: "0238755656230133",
    namaDosen: "JELITA ASIAN.PH.D",
    namaDosenGelar: "Jelita Asian, B.MSc (Hon)., Ph.D.",
    programStudi: "Ilmu Komputer (S3)",
    jabatanAkademik: "Lektor Kepala",
    tmtJad: "01 Juni 2025",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/d",
    tmtInpassing: "01 Januari 2026",
    pendidikanS3: "Doctor of Pilosophy",
  },
  {
    NIDN: "0315046903",
    NUPTK: "8747747648230152",
    namaDosen: "MEDIA ANUGERAH AYU",
    namaDosenGelar: "Prof. Ir. Media Anugerah Ayu, M.Sc., Ph.D.",
    programStudi: "Ilmu Komputer (S3)",
    jabatanAkademik: "Guru Besar",
    tmtJad: "01 Desember 2019",
    Inpassing: "Pembina Tingkat I, golongan ruang IV/b",
    tmtInpassing: "01 Januari 2024",
    pendidikanS2: "Master of Science",
    pendidikanS3: "Doctor of Philosophy",
  },
  {
    NIDN: "0323096491",
    NUPTK: "0255742643130073",
    namaDosen: "TEDDY MANTORO",
    namaDosenGelar: "Prof. Dr. Ir. Teddy Mantoro, M.Sc.",
    programStudi: "Ilmu Komputer (S3)",
    jabatanAkademik: "Guru Besar",
    tmtJad: "01 Oktober 2016",
    Inpassing: "Pembina Utama Madya, golongan ruang IV/d",
    tmtInpassing: "01 Januari 2025",
    pendidikanS2: "Master of Science",
    pendidikanS3: "Doctor of Philosophy",
  },
  {
    NIDN: "0424068107",
    NUPTK: "1956759660130172",
    namaDosen: "UMAR ADITIAWARMAN",
    namaDosenGelar: "Umar Aditiawarman, S.T., M.Sc., Ph.D.",
    programStudi: "Ilmu Komputer (S3)",
    jabatanAkademik: "Lektor Kepala",
    tmtJad: "01 April 2025",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/d",
    tmtInpassing: "01 Januari 2026",
    pendidikanS2: "Master of Information Technology",
    pendidikanS3: "Doctor of Philosophy",
  },
  {
    NIDN: "0416127102",
    NUPTK: "2548749650230113",
    namaDosen: "DESHINTA ARROVA DEWI",
    namaDosenGelar: "Deshinta Arrova Dewi, S.T., M.T., Ph.D.",
    programStudi: "Informatika (S2)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 Maret 2000",
    pendidikanS2: "Magister Teknik",
    pendidikanS3: "Doctor of Pilosophy",
  },
  {
    NIDN: "0415108006",
    NUPTK: "1347758659230203",
    namaDosen: "DINI OKTARINA DWI HANDAYANI",
    namaDosenGelar: "Dini Oktarina Dwi Handayani, S.T., M.T., Ph.D.",
    programStudi: "Informatika (S2)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 Oktober 2019",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "01 Maret 2020",
    pendidikanS2: "Master of Information Technology",
    pendidikanS3: "Doctor of Pilosophy",
  },
  {
    NIDN: "0418068505",
    NUPTK: "5950763664130262",
    namaDosen: "HARIS AL QODRI MAARIF",
    namaDosenGelar: "Haris Al Qodri Maarif, S.T., M.Sc., Ph.D.",
    programStudi: "Informatika (S2)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 Agustus 2022",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "01 Desember 2022",
    pendidikanS2: "Master of Science",
    pendidikanS3: "Doctor of Pilosophy",
  },
  {
    NIDN: "8978490024",
    namaDosen: "HUANG GAN",
    programStudi: "Informatika (S2)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 Oktober 2021",
    pendidikanS2: "Master of Engineering",
    pendidikanS3: "Ph. D. in Engineering ( Computer Engineering)",
  },
  {
    NIDN: "0303037304",
    NUPTK: "8635751652130152",
    namaDosen: "ADHI KUSNADI",
    namaDosenGelar: "Dr. Adhi Kusnadi, M.Si.",
    programStudi: "Informatika (S2)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 September 2017",
    Inpassing: "Penata Tk. I, golongan ruang III/d",
    tmtInpassing: "01 Januari 2020",
    pendidikanS2: "Magister Sains",
  },
  {
    NIDN: "0419077007",
    NUPTK: "7051748649130113",
    namaDosen: "ABU BAKAR",
    namaDosenGelar: "Abu Bakar, S.Sos., M.M.",
    programStudi: "Manajemen (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 Juni 2021",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 Desember 2021",
    pendidikanS2: "Magister Manajemen",
  },
  {
    NIDN: "0412089501",
    NUPTK: "6144773674130243",
    namaDosen: "AGUNG MAULANA",
    namaDosenGelar: "Agung Maulana, S.E., M.A.",
    programStudi: "Manajemen (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 Juli 2025",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "01 Januari 2026",
    pendidikanS2: "Master of Arts",
  },
  {
    NIDN: "0414079101",
    NUPTK: "9046769670230333",
    namaDosen: "ANA YULIANA JASUNI",
    namaDosenGelar: "Ana Yuliana Jasuni, S.E., M.M.",
    programStudi: "Manajemen (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 Desember 2022",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 Februari 2023",
    pendidikanS2: "Magister Manajemen",
    jabatan_struktural: "Ketua Prodi Manajemen",
  },
  {
    NIDN: "0428049204",
    NUPTK: "3760770671130282",
    namaDosen: "ANDRI ARDHIYANSYAH",
    namaDosenGelar: "Andri Ardhiyansyah, S.Hut., M.B.A.",
    programStudi: "Manajemen (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 Maret 2025",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 Mei 2023",
    pendidikanS2: "Master Administrasi Bisnis",
  },
  {
    NIDN: "0417098804",
    NUPTK: "2249766667130293",
    namaDosen: "ARIEF FIRMANTO",
    namaDosenGelar: "Arief Firmanto, S.Kom., M.M.",
    programStudi: "Manajemen (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "02 Mei 2024",
    pendidikanS2: "Magister Manajemen",
  },
  {
    NIDN: "0424108603",
    NUPTK: "9356764665131073",
    namaDosen: "BAGJA RAHMA PUTRA",
    namaDosenGelar: "Bagja Rahma Putra, S.E., M.M.",
    programStudi: "Manajemen (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 Februari 2023",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 Mei 2023",
    pendidikanS2: "Magister Manajemen",
  },
  {
    NIDN: "0405119301",
    NUPTK: "2437771672130173",
    namaDosen: "BONSE ARIS MANDALA PUTRA SIMANGUNSONG",
    namaDosenGelar: "Bonse Aris Mandala Putra Simangunsong, S.Pd., M.M.",
    programStudi: "Manajemen (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 Agustus 2025",
    Inpassing: "Peneta, golongan ruang III/c",
    tmtInpassing: "01 Januari 2026",
    pendidikanS2: "Magister Manajemen",
  },
  {
    NUPTK: "7658765666230252",
    namaDosen: "CHIQUITA MAHARANI",
    namaDosenGelar: "Chiquita Maharani, S.I.Kom., M.M.",
    programStudi: "Manajemen (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "01 Desember 2023",
    pendidikanS2: "Magister Manajemen",
  },
  {
    NIDN: "8945420021",
    NUPTK: "9648740641130062",
    namaDosen: "DANA BUDIMAN",
    namaDosenGelar: "Dr. Ir. Dana Budiman, M.Si.",
    programStudi: "Manajemen (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 April 2022",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "01 Januari 2023",
    pendidikanS2: "Magister Sains",
    pendidikanS3: "Doktor Ilmu Manajemen",
  },
  {
    NIDN: "0420028304",
    NUPTK: "3552761662237042",
    namaDosen: "FITRINA LESTARI",
    namaDosenGelar: "Fitrina Lestari, S.Si., M.A.B.",
    programStudi: "Manajemen (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 Agustus 2025",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 Mei 2023",
    pendidikanS2: "Magister Administrasi Bisnis",
  },
  {
    NIDN: "2125129404",
    namaDosen: "IKMALUL MIFTAH. Z",
    namaDosenGelar: "Ikmalul Miftah Zainutthalibien, S.E., M.A.B.",
    programStudi: "Manajemen (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "01 Desember 2023",
    pendidikanS2: "Magister Administrasi Bisnis",
  },
  {
    NIDN: "0413099803",
    NUPTK: "8245776677230093",
    namaDosen: "INTAN DEANIDA PRATIWI",
    namaDosenGelar: "Intan Deanida Pratiwi, S.A.B., M.M.",
    programStudi: "Manajemen (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 Juni 2025",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 Juli 2025",
    pendidikanS2: "Magister Manajemen",
  },
  {
    NIDN: "0429128506",
    NUPTK: "6561763664130223",
    namaDosen: "KALFAJRIN KURNIAJI",
    namaDosenGelar: "Kalfajrin Kurniaji, S.ST., M.M., MBA.",
    programStudi: "Manajemen (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 Juni 2023",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 November 2023",
    pendidikanS2: "Magister Manajemen",
  },
  {
    NIDN: "0412118403",
    NUPTK: "7444762663137053",
    namaDosen: "KHARISMA",
    namaDosenGelar: "Kharisma, S.ST., M.AB.",
    programStudi: "Manajemen (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 Juli 2020",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 Desember 2020",
    pendidikanS2: "Magister Administrasi Bisnis",
  },
  {
    NIDN: "0402068703",
    NUPTK: "7934765666130332",
    namaDosen: "M. ANDRI JUNIANSYAH",
    namaDosenGelar: "M. Andri Juniansyah, S.E., M.M.",
    programStudi: "Manajemen (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 Januari 2023",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 Mei 2023",
    pendidikanS2: "Magister Manajemen",
  },
  {
    NIDN: "0404039601",
    NUPTK: "2636774675230192",
    namaDosen: "MARINA",
    namaDosenGelar: "Marina, S.Pd., M.M.",
    programStudi: "Manajemen (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 Juni 2023",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 November 2023",
    pendidikanS2: "Magister Manajemen",
  },
  {
    NIDN: "0406118804",
    NUPTK: "1438766667231083",
    namaDosen: "MAULITA LUTFIANI",
    namaDosenGelar: "Maulita Lutfiani, S.E., M.M.",
    programStudi: "Manajemen (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 Juni 2023",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 November 2023",
    pendidikanS2: "Magister Manajemen",
  },
  {
    NIDN: "0320057406",
    NUPTK: "9852752653231092",
    namaDosen: "MEILIANI LUCKIETA",
    namaDosenGelar: "Dr. Meiliani Luckieta, S.E., M.M.",
    programStudi: "Manajemen (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 Juni 2023",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "01 Juli 2025",
    pendidikanS2: "Magister Manajemen",
    pendidikanS3: "Doktor Manajemen",
  },
  {
    NIDN: "0406119301",
    NUPTK: "8438771672130273",
    namaDosen: "MUHAMAD WAHYU HAMIJAYA",
    namaDosenGelar: "Muhamad Wahyu Hamijaya, S.E., M.M.",
    programStudi: "Manajemen (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 Agustus 2025",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "01 Januari 2026",
    pendidikanS2: "Magister Manajemen",
  },
  {
    NIDN: "0428018004",
    NUPTK: "9460758659230112",
    namaDosen: "NIA SONANI",
    namaDosenGelar: "Nia Sonani, S.E., M.M.",
    programStudi: "Manajemen (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 Desember 2021",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "01 Januari 2023",
    pendidikanS2: "Magister Manajemen",
  },
  {
    NIDN: "0422029502",
    NUPTK: "6557773674230132",
    namaDosen: "REKA RAMADHAN",
    namaDosenGelar: "Reka Ramadhan, S.Si., M.Pd.",
    programStudi: "Manajemen (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 Juni 2023",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 Januari 2024",
    pendidikanS2: "Magister Pendidikan",
  },
  {
    NIDN: "0403019204",
    NUPTK: "4435770671230292",
    namaDosen: "RENA YULIANA",
    namaDosenGelar: "Rena Yuliana, S.Pd., M.E.",
    programStudi: "Manajemen (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 Juli 2023",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 Januari 2024",
    pendidikanS2: "Magister Ekonomi",
  },
  {
    NIDN: "0419069402",
    NUPTK: "9951772673130232",
    namaDosen: "RIYAN MIRDAN FARIS",
    namaDosenGelar: "Riyan Mirdan Faris, S.E., M.Si.",
    programStudi: "Manajemen (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 Juni 2025",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "01 Januari 2026",
    pendidikanS2: "Magister Sains",
  },
  {
    NIDN: "0408079005",
    NUPTK: "9040768669231033",
    namaDosen: "RR AMANNA DZIKRILLAH L L",
    namaDosenGelar:
      "Raden Roro Amanna Dzikrillah Lazuardini Luqman Al Hakim, S.S., M.A.B.",
    programStudi: "Manajemen (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 Juni 2025",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "01 Januari 2026",
    pendidikanS2: "Magister Administrasi Bisnis",
  },
  {
    NIDN: "0409058606",
    NUPTK: "7841764665230282",
    namaDosen: "SALIX FINI MARIS",
    namaDosenGelar: "Salix Fini Maris, S.TP., M.M.",
    programStudi: "Manajemen (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 Juli 2023",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 Januari 2024",
    pendidikanS2: "Magister Manajemen",
  },
  {
    NIDN: "8983170023",
    namaDosen: "SATISH KUMAR DAMODAR",
    programStudi: "Manajemen (S1)",
    jabatanAkademik: "Lektor",
    pendidikanS2: "Master of Engineering",
    pendidikanS3: "Doktor of Philosophy",
  },
  {
    NIDN: "0413129601",
    NUPTK: "6545774675230173",
    namaDosen: "SITI NUR AISYAH",
    namaDosenGelar: "Siti Nur Aisyah, S.M., M.A.",
    programStudi: "Manajemen (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 Maret 2025",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 April 2025",
    pendidikanS2: "Master of Arts",
  },
  {
    NIDN: "0416107003",
    NUPTK: "7348748649230083",
    namaDosen: "SITTI HIKMAWATTY",
    namaDosenGelar: "Dr. Sitti Hikmawatty, S.ST., M.Pd.",
    programStudi: "Manajemen (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    pendidikanS2: "Magister Pendidikan",
    pendidikanS3: "Doktor ilmu manajemen",
  },
  {
    NIDN: "0404049302",
    namaDosen: "THESSA TRI ASTUTY",
    namaDosenGelar: "Thessa Tri Astuty, SE., M.M.",
    programStudi: "Manajemen (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "12 Januari 2024",
    pendidikanS2: "Magister Manajemen",
  },
  {
    NIDN: "0402056302",
    NUPTK: "8834741642130102",
    namaDosen: "UMAR MANSUR",
    namaDosenGelar: "Drs. Umar Mansur, S.IP., M.M.",
    programStudi: "Manajemen (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 Agustus 2025",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/a",
    tmtInpassing: "01 April 2019",
    pendidikanS2: "Magister Manajemen",
  },
  {
    NIDN: "0422029304",
    NUPTK: "1554771672230232",
    namaDosen: "VIRANIE DWI MONIKAWATIE",
    namaDosenGelar: "Viranie Dwi Monikawatie, M.Pd.",
    programStudi: "Manajemen (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "01 Maret 2022",
    pendidikanS2: "Magister Pendidikan",
  },
  {
    NIDN: "0404049105",
    NUPTK: "6736769670130412",
    namaDosen: "WAHYU MULYADI",
    namaDosenGelar: "Wahyu Mulyadi, S.AB., M.Si.",
    programStudi: "Manajemen (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 Juni 2024",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 April 2025",
    pendidikanS2: "Magister Sains",
  },
  {
    NIDN: "0410128201",
    NUPTK: "7542760661230253",
    namaDosen: "YULI DIANI RAHMAWATI",
    namaDosenGelar: "Yuli Diani Rahmawati, S.Pd., M.M.",
    programStudi: "Manajemen (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "01 September 2023",
    pendidikanS2: "Magister Manajemen",
  },
  {
    NIDN: "0317086202",
    NUPTK: "2149740641130163",
    namaDosen: "GUSTIAN DJUANDA",
    namaDosenGelar: "Dr. H. Gustian Djuanda, S.E., M.M.",
    programStudi: "Manajemen (S2)",
    jabatanAkademik: "Lektor Kepala",
    tmtJad: "01 Mei 2009",
    Inpassing: "Pembina, golongan ruang IV/a",
    tmtInpassing: "01 Desember 2020",
    pendidikanS2: "Magister Manajemen",
    pendidikanS3: "Doktor Ekonomi Islam",
  },
  {
    NIDN: "0407036606",
    NUPTK: "2639744645230122",
    namaDosen: "HESRI MINTAWATI",
    namaDosenGelar: "Dr. Hesri Mintawati, S.Pd., M.M.",
    programStudi: "Manajemen (S2)",
    jabatanAkademik: "Lektor Kepala",
    tmtJad: "01 Juli 2025",
    Inpassing: "Penata Tk. I, golongan ruang III/d",
    tmtInpassing: "01 Januari 2026",
    pendidikanS2: "Magister Manajemen",
    pendidikanS3: "Doctor of Philosophy",
  },
  {
    NIDN: "8957560023",
    NUPTK: "8046730631130043",
    namaDosen: "KOESMAWAN",
    namaDosenGelar: "Dr. Ir. Koesmawan, M.Sc., MBA., DBA.",
    programStudi: "Manajemen (S2)",
    jabatanAkademik: "Guru Besar",
    tmtJad: "01 Desember 2003",
    pendidikanS2: "Master of Business Administration",
    pendidikanS3: "Doctor of Business Administration",
  },
  {
    NIDN: "0410087407",
    NUPTK: "0142752653130173",
    namaDosen: "KURNIAWAN",
    namaDosenGelar: "Dr. Kurniawan, S.T., M.M., M.Si.",
    programStudi: "Manajemen (S2)",
    jabatanAkademik: "Lektor Kepala",
    tmtJad: "01 Juli 2022",
    Inpassing: "Pembina, golongan ruang IV/a",
    tmtInpassing: "01 Januari 2025",
    pendidikanS2: "Magister Ilmu Administrasi, Magister Manajemen",
    pendidikanS3: "Doktor",
  },
  {
    NIDN: "0429087304",
    NUPTK: "9161751652130083",
    namaDosen: "NUR HASAN KURNIAWAN",
    namaDosenGelar: "Dr. Nur Hasan Kurniawan, S.E., M.M.",
    programStudi: "Manajemen (S2)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "19 April 2024",
    pendidikanS2: "Magister Ilmu Profesi Jalur Profesi",
    pendidikanS3: "Doktor",
  },
  {
    NIDN: "0307028902",
    NUPTK: "0539767668130312",
    namaDosen: "SLAMET SUTRISNO",
    namaDosenGelar: "Dr. Slamet Sutrisno, S.T., M.M.",
    programStudi: "Manajemen (S2)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 Agustus 2025",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "01 Januari 2026",
    pendidikanS2: "Magister Manajemen",
    pendidikanS3: "Doktor",
  },
  {
    NIDN: "4355772673130273",
    NUPTK: "4355772673130273",
    namaDosen: "AGUS HENDRIYANTO",
    namaDosenGelar: "Dr. Agus Hendriyanto, M.Pd.",
    programStudi: "Pedagogi (S2)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "12 September 2024",
    pendidikanS2: "Magister Pendidikan",
    pendidikanS3: "Doktor - Pendidikan Matematika",
  },
  {
    NIDN: "0415087009",
    NUPTK: "7147748649130193",
    namaDosen: "AYI ABDURAHMAN",
    namaDosenGelar: "Dr. Ayi Abdurahman, S.Pd.I., S.E., M.M., M.Pd.",
    programStudi: "Pedagogi (S2)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 April 2022",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "01 Januari 2023",
    pendidikanS2: "Magister Ilmu Pendidikan, Magister Manajemen",
    pendidikanS3: "Doctor Ilmu Pendidikan",
  },
  {
    NIDN: "0414090901",
    NUPTK: "7148754655130133",
    namaDosen: "DR H BARKAH SPD MPD",
    namaDosenGelar: "Dr. Barkah, S.Pd., M.Pd.",
    programStudi: "Pedagogi (S2)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 Maret 2022",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "01 Januari 2023",
    pendidikanS2: "Magister Pendidikan",
    pendidikanS3: "Doktor - Pendidikan Bahasa Indonesia",
  },
  {
    NIDN: "0427118201",
    NUPTK: "6459760661237003",
    namaDosen: "DYAH LYESMAYA",
    namaDosenGelar: "Dr. Dyah Lyesmaya, S.Pd., M.M.",
    programStudi: "Pedagogi (S2)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 Oktober 2019",
    Inpassing: "Penata, golongan ruang III/d",
    tmtInpassing: "01 Januari 2022",
    pendidikanS2: "Magister Pendidikan",
    pendidikanS3: "Doktor Pendidikan Dasar",
  },
  {
    NIDN: "8906160022",
    NUPTK: "7534729630130013",
    namaDosen: "MUHIBBIN SYAH",
    namaDosenGelar: "Dr. Muhibbin Syah, M.Ed.",
    programStudi: "Pedagogi (S2)",
    jabatanAkademik: "Guru Besar",
    tmtJad: "01 Desember 2010",
    pendidikanS2: "Master of Educational Studies",
    pendidikanS3: "Doktor - Administrasi Pendidikan",
  },
  {
    NIDN: "0429126903",
    NUPTK: "7561747650300053",
    namaDosen: "UCU AGUSTINI SRI MULYANI",
    namaDosenGelar: "Dr. Ucu Agustini Sri Mulyani, S.Pd.I., M.Pd.",
    programStudi: "Pedagogi (S2)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 Juni 2025",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "01 Juli 2025",
    pendidikanS2: "Magister Pendidikan",
    pendidikanS3: "Doktor - Manajemen Pendidiakn",
  },
  {
    NIDN: "0429126903",
    NUPTK: "9351744645130063",
    namaDosen: "UJANG SYARIP HIDAYAT",
    namaDosenGelar: "Dr. Ujang Syarip Hidayat, S.Pd., M.Pd.",
    programStudi: "Pedagogi (S2)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 April 2022",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "01 Januari 2023",
    pendidikanS2: "Magister Administrasi Pendidikan",
    pendidikanS3: "Doktor Ilmu Pendidikan",
  },
  {
    NIDN: "0401056501",
    NUPTK: "6863743644230062",
    namaDosen: "WIWIN WINARNI",
    namaDosenGelar: "Dr. Wiwin Winarni, Dra., M.M.Pd.",
    programStudi: "Pedagogi (S2)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 Mei 2022",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "01 Januari 2023",
    pendidikanS2: "Magister Manajemen Pendidikan",
    pendidikanS3: "Doctor Ilmu Pendidikan",
  },
  {
    NIDN: "0419047405",
    NUPTK: "4751752653300032",
    namaDosen: "WULAN WIDANINGSIH",
    namaDosenGelar: "Dr. Wulan Widaningsih, M.Pd.",
    programStudi: "Pedagogi (S2)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "09 Agustus 2021",
    pendidikanS2: "Magister Pendidikan Bahasa",
    pendidikanS3: "Doktor - Manajemen Pendidikan",
  },
  {
    NIDN: "0411019503",
    NUPTK: "8443773674230222",
    namaDosen: "ANY ELVIA JAKFAR",
    namaDosenGelar: "Any Elvia Jakfar, S.Psi., M.A.",
    programStudi: "Pendidikan Guru Sekolah Dasar (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 November 2024",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 April 2025",
    pendidikanS2: "Master of Arts",
  },
  {
    NIDN: "8898290019",
    NUPTK: "3361765667110023",
    namaDosen: "BUDI KURNIA",
    namaDosenGelar: "Budi Kurnia, S.Pd., M.Pd.",
    programStudi: "Pendidikan Guru Sekolah Dasar (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 November 2022",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 Maret 2023",
    pendidikanS2: "Magister Pendidikan",
  },
  {
    NIDN: "0423109403",
    NUPTK: "8355772673230243",
    namaDosen: "DHEA ADELA",
    namaDosenGelar: "Dhea Adela, S.Pd., M.Pd.",
    programStudi: "Pendidikan Guru Sekolah Dasar (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 Desember 2024",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "01 Januari 2026",
    pendidikanS2: "Magister Pendidikan",
  },
  {
    NIDN: "0419078905",
    NUPTK: "0051767668210003",
    namaDosen: "DINDA ANDIANA",
    namaDosenGelar: "Dinda Andiana, S.Pd., M.Pd.",
    programStudi: "Pendidikan Guru Sekolah Dasar (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 Agustus 2022",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 Desember 2022",
    pendidikanS2: "Magister Pendidikan",
  },
  {
    NIDN: "0412039401",
    NUPTK: "6644772673230262",
    namaDosen: "FITRIA NURULAENI",
    namaDosenGelar: "Fitria Nurulaeni, S.Pd., M.Pd.",
    programStudi: "Pendidikan Guru Sekolah Dasar (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 Desember 2024",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "01 Januari 2026",
    pendidikanS2: "Magister Pendidikan",
  },
  {
    NIDN: "8930850022",
    NUPTK: "2056752653300033",
    namaDosen: "IA HIDARYA",
    namaDosenGelar: "Dr. Ia Hidarya, S.Pd.I., M.M.",
    programStudi: "Pendidikan Guru Sekolah Dasar (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 Maret 2024",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "01 Mei 2024",
    pendidikanS2: "Magister Manajemen",
    pendidikanS3: "Doktor - Ilmu Pendidikan",
  },
  {
    NIDN: "0405088204",
    NUPTK: "6137760661130233",
    namaDosen: "IRFAN SOFIAN",
    namaDosenGelar: "Irfan Sofian, S.Pd.I., M.Pd.",
    programStudi: "Pendidikan Guru Sekolah Dasar (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 Agustus 2025",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 September 2025",
    pendidikanS2: "Magister Pendidikan",
  },
  {
    NIDN: "8815723420",
    NUPTK: "5461749650200003",
    namaDosen: "IWAN GUNAWAN",
    namaDosenGelar: "Iwan Gunawan, S.Pd., M.M.",
    programStudi: "Pendidikan Guru Sekolah Dasar (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "31 Oktober 2018",
    pendidikanS2: "Magister Manajemen",
  },
  {
    NIDN: "0409109502",
    NUPTK: "4341773674130223",
    namaDosen: "JOKO SUPRAPMANTO",
    namaDosenGelar: "Joko Suprapmanto, S.Pd., M.Pd.",
    programStudi: "Pendidikan Guru Sekolah Dasar (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 Desember 2024",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 Desember 2022",
    pendidikanS2: "Magister Pendidikan",
  },
  {
    NIDN: "8861500016",
    NUPTK: "3139747650200073",
    namaDosen: "KOHAR PRADESA",
    namaDosenGelar: "Dr. Kohar Pradesa, S.Pd., M.Pd.",
    programStudi: "Pendidikan Guru Sekolah Dasar (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 Maret 2020",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "01 Juni 2020",
    pendidikanS2: "Magister Pendidikan",
    pendidikanS3: "Doktor - Pendidikan Umum",
  },
  {
    NIDN: "0401077707",
    NUPTK: "8033755655300003",
    namaDosen: "LINA HERLINA",
    namaDosenGelar: "Lina Herlina, S.Pd., M.Pd.",
    programStudi: "Pendidikan Guru Sekolah Dasar (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 Juli 2023",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "01 Januari 2024",
    pendidikanS2: "Magister Pendidikan",
  },
  {
    NIDN: "0423058902",
    NUPTK: "5855767668230282",
    namaDosen: "MELSYA FIRTIKASARI",
    namaDosenGelar: "Melsya Firtikasari, S.Pd., M.Sn.",
    programStudi: "Pendidikan Guru Sekolah Dasar (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 Juli 2025",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "01 Januari 2026",
    pendidikanS2: "Magister Seni",
  },
  {
    NIDN: "2112067905",
    namaDosen: "MOHAMAD NAJIB",
    namaDosenGelar: "Mohamad Najib, S.Pd., M.Pd.",
    programStudi: "Pendidikan Guru Sekolah Dasar (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 Agustus 2022",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 Desember 2022",
    pendidikanS2: "Magister Pendidikan",
  },
  {
    NIDN: "0427039305",
    NUPTK: "6659771672130312",
    namaDosen: "RINALDI YUSUP",
    namaDosenGelar: "Rinaldi Yusup, S.Pd., M.Pd.",
    programStudi: "Pendidikan Guru Sekolah Dasar (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 Juli 2024",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 September 2024",
    pendidikanS2: "Magister Pendidikan",
  },
  {
    NIDN: "8970670023",
    NUPTK: "7938740644200012",
    namaDosen: "SAJIDIN",
    namaDosenGelar: "Sajidin, S.Pd., M.M.Pd.",
    programStudi: "Pendidikan Guru Sekolah Dasar (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "01 September 2022",
    pendidikanS2: "Magister Manajemen Pendidikan",
  },
  {
    NIDN: "0403048803",
    NUPTK: "3735766667130322",
    namaDosen: "SAMSUL PAHMI",
    namaDosenGelar: "Samsul Pahmi, S.Pd., M.Pd.",
    programStudi: "Pendidikan Guru Sekolah Dasar (S1)",
    jabatanAkademik: "Lektor Kepala",
    tmtJad: "01 Desember 2023",
    Inpassing: "Penata Tk. I, golongan ruang III/d",
    tmtInpassing: "01 Januari 2025",
    pendidikanS2: "Magister Pendidikan",
  },
  {
    NIDN: "0429129401",
    NUPTK: "8561772673230253",
    namaDosen: "SHERYL MUTIARA PUTRI",
    namaDosenGelar: "Sheryl Mutiara Putri, S.Pd., M.Pd.",
    programStudi: "Pendidikan Guru Sekolah Dasar (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 Juni 2025",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 Juli 2025",
    pendidikanS2: "Magister Pendidikan ",
  },
  {
    NIDN: "8971530021",
    NUPTK: "6433739641300202",
    namaDosen: "SRI ERWINI CHRISTINE",
    namaDosenGelar: "Dr. Sri Erwini Christine, Dra., M.M.Pd.",
    programStudi: "Pendidikan Guru Sekolah Dasar (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 Juni 2022",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "01 Januari 2023",
    pendidikanS2: "Magister Manajemen Pendidikan",
    pendidikanS3: "Doktor - Adminstrasi Pendidikan",
  },
  {
    NIDN: "0425079003",
    NUPTK: "6057768669130293",
    namaDosen: "TEOFILUS ARDIAN HOPEMAN",
    namaDosenGelar: "Teofilus Ardian Hopeman, S.Pd., M.Pd.",
    programStudi: "Pendidikan Guru Sekolah Dasar (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 Maret 2025",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 Mei 2023",
    pendidikanS2: "Magister Pendidikan",
  },
  {
    NIDN: "0428036102",
    NUPTK: "4660739640130042",
    namaDosen: "UTOMO",
    namaDosenGelar: "Utomo, S.Pd., M.M.",
    programStudi: "Pendidikan Guru Sekolah Dasar (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 April 2024",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "01 Januari 2026",
    pendidikanS2: "Magister Manajemen",
    jabatan_struktural: "Ketua Prodi Pendidikan Guru Sekolah Dasar",
  },
  {
    NIDN: "0417049102",
    NUPTK: "6749769670130332",
    namaDosen: "ADHITIA ERFINA",
    namaDosenGelar: "Adhitia Erfina, S.T., M.Kom.",
    programStudi: "Sistem Informasi (S1)",
    jabatanAkademik: "Lektor Kepala",
    tmtJad: "01 Juni 2025",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "01 Januari 2024",
    pendidikanS2: "Magister Komputer",
  },
  {
    NIDN: "0424089206",
    NUPTK: "8156770671230313",
    namaDosen: "ARNY LATTU",
    namaDosenGelar: "Arny Lattu, S.Pd.Kom., M.Kom.",
    programStudi: "Sistem Informasi (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 Maret 2025",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 Maret 2023",
    pendidikanS2: "Magister Sistem Informasi",
  },
  {
    NIDN: "8925420021",
    NUPTK: "0649745646130092",
    namaDosen: "ASEP ZUHARA ARGAWINATA",
    namaDosenGelar: "Dr. Asep Zuhara Argawinata, S.I.Kom., M.I.Kom.",
    programStudi: "Sistem Informasi (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "01 Febriari 2021",
    pendidikanS2: "Magister Ilmu Komunikasi",
    pendidikanS3: "Doktor",
  },
  {
    NIDN: "0401108606",
    NUPTK: "1333764665230283",
    namaDosen: "CARTI IRAWAN",
    namaDosenGelar: "Carti Irawan, S.Kom., M.Kom.",
    programStudi: "Sistem Informasi (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 April 2023",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 September 2023",
    pendidikanS2: "Magister Komputer",
  },
  {
    NIDN: "6038748649130213",
    NUPTK: "6038748649130213",
    namaDosen: "CECEP WARMAN",
    namaDosenGelar: "Cecep Warman, S.Kom., M.Kom.",
    programStudi: "Sistem Informasi (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "03 Mareti 2023",
    pendidikanS2: "Magister Komputer",
  },
  {
    NIDN: "0405119501",
    NUPTK: "8437773674130243",
    namaDosen: "DEDE SUKMAWAN",
    namaDosenGelar: "Dede Sukmawan, S.Kom., M.Kom.",
    programStudi: "Sistem Informasi (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 April 2023",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 September 2023",
    pendidikanS2: "Magister Komputer",
  },
  {
    NIDN: "0410016703",
    NUPTK: "5442745646130122",
    namaDosen: "DENI HASMAN",
    namaDosenGelar: "Ir. Deni Hasman, M.P.",
    programStudi: "Sistem Informasi (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 November 2018",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 November 2019",
    pendidikanS2: "Magister Profesional",
    pendidikanS3: "Doktor Teknologi Pendidikan",
  },
  {
    NIDN: "0405088001",
    NUPTK: "2137758660200013",
    namaDosen: "DUDIH GUSTIAN",
    namaDosenGelar: "Dudih Gustian, S.Kom., M.Kom.",
    programStudi: "Sistem Informasi (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 Agustus 2019",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "01 Januari 2022",
    pendidikanS2: "Magister Ilmu Komputer",
  },
  {
    NIDN: "0408029102",
    NUPTK: "2540769670130272",
    namaDosen: "FALENTINO SEMBIRING",
    namaDosenGelar: "Falentino Sembiring, S.Kom., M.Kom.",
    programStudi: "Sistem Informasi (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 September 2022",
    Inpassing: "Penata Tk. I, golongan ruang III/d",
    tmtInpassing: "01 Januari 2026",
    pendidikanS2: "Magister Sistem Informasi",
    jabatan_struktural: "Ketua Prodi Sistem Informasi",
  },
  {
    NIDN: "0417087609",
    NUPTK: "7149754656300053",
    namaDosen: "GINA SYABANI YUDA",
    namaDosenGelar: "Gina Syabani Yuda, M.Pd.",
    programStudi: "Sistem Informasi (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "30 November 2020",
    pendidikanS2: "Magister Pendidikan",
  },
  {
    NIDN: "8959920021",
    NUPTK: "1958740641230122",
    namaDosen: "GIRI VERIANTI",
    namaDosenGelar: "Dr. Giri Verianti, S.Pd., M.Pd.",
    programStudi: "Sistem Informasi (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 September 2022",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "01 Januari 2023",
    pendidikanS2: "Magister Pendidikan",
    pendidikanS3: "Doktor",
  },
  {
    NIDN: "0414069701",
    NUPTK: "7946775676230152",
    namaDosen: "HABI BATUROHMAH",
    namaDosenGelar: "Habi Baturohmah, S.Kom., M.Kom.",
    programStudi: "Sistem Informasi (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 Oktober 2023",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 Januari 2024",
    pendidikanS2: "Magister Komputer",
  },
  {
    NIDN: "0418067208",
    NUPTK: "2950750652200022",
    namaDosen: "HENDRI EKASATRIA",
    namaDosenGelar: "Hendri Ekasatria, M.Kom.",
    programStudi: "Sistem Informasi (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "01 November 2023",
    pendidikanS2: "Magister Ilmu Kompter",
  },
  {
    NIDN: "0404069601",
    NUPTK: "4936774675130242",
    namaDosen: "M. ANTON PERMANA",
    namaDosenGelar: "M. Anton Permana, S.Kom., M.Kom.",
    programStudi: "Sistem Informasi (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 April 2023",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 September 2023",
    pendidikanS2: "Magister Komputer",
  },
  {
    NIDN: "0429038601",
    NUPTK: "8761764665130222",
    namaDosen: "MUHAMAD MUSLIH",
    namaDosenGelar: "Muhamad Muslih, S.T., M.Kom.",
    programStudi: "Sistem Informasi (S1)",
    jabatanAkademik: "Lektor Kepala",
    tmtJad: "01 Maret 2024",
    Inpassing: "Pembina, golongan ruang IV/a",
    tmtInpassing: "01 Januari 2025",
    pendidikanS2: "Magister Ilmu Komputer",
  },
  {
    NIDN: "0414027906",
    NUPTK: "1546757658130122",
    namaDosen: "MUPAAT",
    namaDosenGelar: "Mupaat, S.Kom., M.Kom.",
    programStudi: "Sistem Informasi (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 Januari 2017",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 Maret 2017",
    pendidikanS2: "Magister Ilmu Komputer",
  },
  {
    NIDN: "0404128502",
    NUPTK: "3536763664230213",
    namaDosen: "NUNIK DESTRIA ARIANTI",
    namaDosenGelar: "Nunik Destria Arianti, S.Kom., M.Kom.",
    programStudi: "Sistem Informasi (S1)",
    jabatanAkademik: "Lektor Kepala",
    tmtJad: "01 Desember 2023",
    Inpassing: "Penata Tk. I, golongan ruang III/d",
    tmtInpassing: "01 Januari 2023",
    pendidikanS2: "Magister ilmu Komputer",
  },
  {
    NIDN: "0407058603",
    NUPTK: "1839764666300012",
    namaDosen: "RIESKA RAHAYU AYUNINGSIH",
    namaDosenGelar: "Rieska Rahayu Ayuningsih, S.T., M.Kom.",
    programStudi: "Sistem Informasi (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 April 2024",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 September 2024",
    pendidikanS2: "Magister Komputer",
  },
  {
    NIDN: "0416098506",
    NUPTK: "6848762665200002",
    namaDosen: "SIHABUDIN",
    namaDosenGelar: "Sihabudin, S.T., M.Pd., M.Kom.",
    programStudi: "Sistem Informasi (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 Januari 2023",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 Mei 2023",
    pendidikanS2: "Magister Ilmu Komputer",
  },
  {
    NIDN: "0414088608",
    NUPTK: "2146764665110033",
    namaDosen: "SUDIN SAEPUDIN",
    namaDosenGelar: "Sudin Saepudin, S.Kom., M.Kom.",
    programStudi: "Sistem Informasi (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 Februari 2021",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "01 Januari 2026",
    pendidikanS2: "Magister Komputer",
  },
  {
    NIDN: "8935420021",
    NUPTK: "8446748649130073",
    namaDosen: "SUMARNA",
    namaDosenGelar: "Dr. Sumarna, M.Pd.",
    programStudi: "Sistem Informasi (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "10 Februari 2021",
    pendidikanS2: "Magister Pendidikan",
    pendidikanS3: "Doktor",
  },
  {
    NIDN: "0410058403",
    NUPTK: "5842762663130322",
    namaDosen: "WISUDA JATMIKO",
    namaDosenGelar: "Wisuda Jatmika, M.Kom.",
    programStudi: "Sistem Informasi (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "13 Desember 2016",
    pendidikanS2: "Magister Ilmu Komputer",
  },
  {
    NIDN: "0407098009",
    NUPTK: "9239758659200013",
    namaDosen: "ANANG SURYANA",
    namaDosenGelar: "Anang Suryana, S.Pd., M.Si.",
    programStudi: "Teknik Elektro (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 Desember 2024",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 Januari 2019",
    pendidikanS2: "Magister Sains",
  },
  {
    NIDN: "0425068502",
    NUPTK: "0957763664130282",
    namaDosen: "ANGGY PRADIFTHA JUNFITHRANA",
    namaDosenGelar: "Anggy Pradiftha Junfithrana, S.Pd., M.T.",
    programStudi: "Teknik Elektro (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 Februari 2021",
    Inpassing: "Penata Tk. I, golongan ruang III/d",
    tmtInpassing: "01 Januari 2025",
    pendidikanS2: "Magister Teknik",
  },
  {
    NIDN: "0402128905",
    NUPTK: "6534767668130273",
    namaDosen: "ARYO DE WIBOWO MUHAMMAD SIDIK",
    namaDosenGelar: "Aryo De Wibowo Muhammad Sidik, S.T., M.T.",
    programStudi: "Teknik Elektro (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 Mei 2023",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 April 2021",
    pendidikanS2: "Magister Teknik",
  },
  {
    NIDN: "3637762663130322\t\n",
    NUPTK: "3637762663130322",
    namaDosen: "ASEP DADAN HERMAWAN",
    namaDosenGelar: "Asep Dadan Hermawan, S.T., M.Sc.",
    programStudi: "Teknik Elektro (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "14 September 2023",
    pendidikanS2: "Magister Teknik Elektro",
  },
  {
    NIDN: "0403088504",
    NUPTK: "0135763664131123",
    namaDosen: "BAYU INDRAWAN",
    namaDosenGelar: "Dr. Bayu Indrawan, S.T., M.T.",
    programStudi: "Teknik Elektro (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 Mei 2024",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "01 April 2025",
    pendidikanS2: "Magister Teknik",
    pendidikanS3: "Doctor of Engineering",
  },
  {
    NIDN: "8735775676130202",
    NUPTK: "8735775676130202",
    namaDosen: "FIKRI ARIF WICAKSANA",
    namaDosenGelar: "Fikri Arif Wicaksana, S.Pd., M.T.",
    programStudi: "Teknik Elektro (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "07 Agustus 2024",
    pendidikanS2: "Magister Teknik",
  },
  {
    NIDN: "8965420021",
    NUPTK: "0435767668130283",
    namaDosen: "HANDREA BERNANDO TAMBUNAN",
    namaDosenGelar: "Handrea Bernando Tambunan, S.T., M.Eng.",
    programStudi: "Teknik Elektro (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 Juli 2022",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 Maret 2023",
    pendidikanS2: "Master of Engineering",
  },
  {
    NIDN: "0115066804",
    NUPTK: "1947746647130162",
    namaDosen: "HARURIKSON LUMBANTOBING",
    namaDosenGelar: "Dr. Harurikson Lumbantobing, M.Kes.",
    programStudi: "Teknik Elektro (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 Mei 2018",
    Inpassing: "Penata , golongan ruang III/c",
    tmtInpassing: "01 Januari 2014",
    pendidikanS2: "Magister kedokteran, Magister Kesehatan",
    pendidikanS3: "Doktor",
  },
  {
    NIDN: "0428119102",
    NUPTK: "4460769670130333",
    namaDosen: "ILMAN HIMAWAN KUSUMAH",
    namaDosenGelar: "Ilman Himawan Kusumah, S.Pd., M.T.",
    programStudi: "Teknik Elektro (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 Oktober 2019",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 Maret 2020",
    pendidikanS2: "Magister Teknik",
  },
  {
    NIDN: "0403127308",
    NUPTK: "5535751652230113",
    namaDosen: "MARINA ARTIYASA",
    namaDosenGelar: "Marina Artiyasa, S.T., M.T.",
    programStudi: "Teknik Elektro (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 Februari 2021",
    Inpassing: "Penata , golongan ruang III/c",
    tmtInpassing: "01 Januari 2022",
    pendidikanS2: "Magister Teknik",
  },
  {
    NIDN: "0426019502",
    namaDosen: "MUCHTAR ALI SETYO YUDONO",
    namaDosenGelar: "Muchtar Ali Setyo Yudono, S.T., M.T.",
    programStudi: "Teknik Elektro (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 Oktober 2022",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 Januari 2023",
    pendidikanS2: "Magister Teknik",
  },
  {
    NIDN: "0427047803",
    NUPTK: "0759756657130132",
    namaDosen: "PANJI NARPUTRO",
    namaDosenGelar: "Panji Narputro, S.T., M.T.",
    programStudi: "Teknik Elektro (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "01 Februari 2024",
    pendidikanS2: "Magister Teknik",
    jabatan_struktural: "Ketua Prodi Teknik Elektro",
  },
  {
    NIDN: "0306118401",
    NUPTK: "5438762663231143",
    namaDosen: "RINI KHAMIMATUL ULA",
    namaDosenGelar: "Rini Khamimatul Ula, S.Pd., M.Si., Ph.D.",
    programStudi: "Teknik Elektro (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 Juni 2024",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "01 April 2025",
    pendidikanS2: "Magister Sains",
    pendidikanS3: "Doktor Electrical Engineering",
  },
  {
    NIDN: "0420038701",
    NUPTK: "3652765666230272",
    namaDosen: "TRISIANI DEWI HENDRAWATI",
    namaDosenGelar: "Trisiani Dewi Hendrawati, S.Pd., M.T.",
    programStudi: "Teknik Elektro (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 Maret 2020",
    Inpassing: "Penata , golongan ruang III/c",
    tmtInpassing: "01 Januari 2021",
    pendidikanS2: "Magister Teknik Elektro",
  },
  {
    NIDN: "0428078801",
    NUPTK: "8060766667130303",
    namaDosen: "ADRIAN REZA",
    namaDosenGelar: "Adrian Reza, S.T., M.T.",
    programStudi: "Teknik Informatika (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 Mei 2016",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 September 2016",
    pendidikanS2: "Magister Teknik",
  },
  {
    NIDN: "0718108001",
    NUPTK: "2350758659130163",
    namaDosen: "ALUN SUJJADA",
    namaDosenGelar: "Alun Sujjada, S.Kom., M.T.",
    programStudi: "Teknik Informatika (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 Juni 2024",
    Inpassing: "Penata , golongan ruang III/c",
    tmtInpassing: "01 Januari 2026",
    pendidikanS2: "Magister Teknik",
  },
  {
    NIDN: "0407029301",
    NUPTK: "0539771672230282",
    namaDosen: "ANGGUN FERGINA",
    namaDosenGelar: "Anggun Fergina, S.Kom., M.Kom.",
    programStudi: "Teknik Informatika (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 Desember 2024",
    Inpassing: "Penata , golongan ruang III/c",
    tmtInpassing: "01 Januari 2026",
    pendidikanS2: "Magister Komputer",
  },
  {
    NIDN: "0416079801",
    NUPTK: "2048776677230103",
    namaDosen: "DHITA DIANA DEWI",
    namaDosenGelar: "Dhita Diana Dewi, S.Stat., M.Stat.",
    programStudi: "Teknik Informatika (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 Juni 2024",
    pendidikanS2: "Magister Statitiska Terapan",
  },
  {
    NIDN: "0120220051",
    namaDosen: "DELISMAR",
    namaDosenGelar: "Dr. Delismar, S.Pd., M.Pd.",
    programStudi: "Teknik Informatika (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "19 September 2022",
    pendidikanS2: "Magister Pendidikan IPA",
    pendidikanS3: "Doktor - Pendidikan MIPA",
  },
  {
    NIDN: "0417077908",
    NUPTK: "3049757658230203",
    namaDosen: "GINA PURNAMA INSANY",
    namaDosenGelar: "Gina Purnama Insany, S.ST., M.Kom.",
    programStudi: "Teknik Informatika (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 Juni 2025",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "01 Januari 2026",
    pendidikanS2: "Magister Komputer",
  },
  {
    NIDN: "0402027401",
    NUPTK: "8534752654200002",
    namaDosen: "HERMANTO",
    namaDosenGelar: "Hermanto, S.T., M.Kom.",
    programStudi: "Teknik Informatika (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 April 2024",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 Oktober 2024",
    pendidikanS2: "Magister Informatika",
  },
  {
    NIDN: "0427087802",
    NUPTK: "9159756657130103",
    namaDosen: "IMAM SANJAYA",
    namaDosenGelar: "Imam Sanjaya, S.P., M.Kom.",
    programStudi: "Teknik Informatika (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 Maret 2025",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 April 2025",
    pendidikanS2: "Magister Komputer",
  },
  {
    NIDN: "0409017604",
    NUPTK: "1441754655130092",
    namaDosen: "INDRA YUSTIANA",
    namaDosenGelar: "Indra Yustiana, S.T., M.Kom.",
    programStudi: "Teknik Informatika (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 April 2019",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 November 2019",
    pendidikanS2: "Magister Informatika",
  },
  {
    NIDN: "0429038002",
    NUPTK: "4661758659230142",
    namaDosen: "IVANA LUCIA KHARISMA",
    namaDosenGelar: "Ivana Lucia Kharisma, S.Kom., M.Kom.",
    programStudi: "Teknik Informatika (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 Maret 2025",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 Mei 2023",
    pendidikanS2: "Magister Komputer",
  },
  {
    NIDN: "8955710021",
    NUPTK: "8252754655110023",
    namaDosen: "IWAN SETIAWAN",
    namaDosenGelar: "Dr. Iwan Setiawan, S.T., M.Kom.",
    programStudi: "Teknik Informatika (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "01 Oktober 2020",
    pendidikanS2: "Magister Teknik",
  },
  {
    NIDN: "0401107401",
    NUPTK: "2333752653130113",
    namaDosen: "KAMDAN",
    namaDosenGelar: "Kamdan, S.T., M.Kom.",
    programStudi: "Teknik Informatika (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 Juni 2025",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "01 Januari 2026",
    pendidikanS2: "Magister Komputer",
  },
  {
    NIDN: "0423049702",
    NUPTK: "3755775676230152",
    namaDosen: "LUSIANA SANI PARWATI",
    namaDosenGelar: "Lusiana Sani Parwati, S.Pd., M.Mat.",
    programStudi: "Teknik Informatika (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 November 2024",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 April 2025",
    pendidikanS2: "Magister Matematika",
  },
  {
    NIDN: "0415049302",
    NUPTK: "5747771672130302",
    namaDosen: "MUHAMMAD IKHSAN THOHIR",
    namaDosenGelar: "Muhammad Ikhsan Thohir, S.Kom., M.Kom.",
    programStudi: "Teknik Informatika (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 Juli 2023",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 Januari 2024",
    pendidikanS2: "Magister Komputer",
  },
  {
    NIDN: "0413098904",
    NUPTK: "1245767668130323",
    namaDosen: "NUGRAHA",
    namaDosenGelar: "Nugraha, S.Kom., M.Kom.",
    programStudi: "Teknik Informatika (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "25 Februari 2025",
    pendidikanS2: "Magister Komputer",
  },
  {
    NIDN: "8988560023",
    NUPTK: "6644748649130122",
    namaDosen: "NURKHAN",
    namaDosenGelar: "Dr. H. Nurkhan, M.Ag.",
    programStudi: "Teknik Informatika (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "07 September 2022",
    pendidikanS2: "Magister Agama",
    pendidikanS3: "Doctor Ilmu Pendidikan ",
  },
  {
    NIDN: "8880001019",
    NUPTK: "4560744644200003",
    namaDosen: "NUZWAN SUDARIANA",
    namaDosenGelar: "Drs. Nuzwan Sudariana, M.M.",
    programStudi: "Teknik Informatika (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "10 Februari 2020",
    pendidikanS2: "Magister Manajemen",
  },
  {
    NIDN: "0120220041",
    namaDosen: "RUMYATI",
    namaDosenGelar: "Dr. Rumyati, M.Pd.",
    programStudi: "Teknik Informatika (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "23 Agustus 2022",
    pendidikanS2: "Magister Teknologi Pendidikan ",
    pendidikanS3: "Doktor Penelitian dan Evaluasi Pendidikan",
  },
  {
    NIDN: "8941530021",
    NUPTK: "4944737640300022",
    namaDosen: "SETIAWATI",
    namaDosenGelar: "Dr. Setiawati, S.Pd.SD., M.Pd.",
    programStudi: "Teknik Informatika (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 Mei 2022",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "01 Januari 2023",
    pendidikanS2: "Magister Pendidikan",
    pendidikanS3: "Doktor Ilmu Pendidikan",
  },
  {
    NIDN: "0419128801",
    NUPTK: "4547766667110013",
    namaDosen: "SOMANTRI",
    namaDosenGelar: "Ir. Somantri, S.T., M.Kom.",
    programStudi: "Teknik Informatika (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 Januari 2023",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "01 Januari 2024",
    pendidikanS2: "Magister Informatika",
    jabatan_struktural: "Ketua Prodi Teknik Informatika",
  },
  {
    NIDN: "8875823420 ",
    namaDosen: "SUPRAPTO",
    namaDosenGelar: "Suprapto, S.Kp., M.M.",
    programStudi: "Teknik Informatika (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: 6613904,
    pendidikanS2: "Magister Manajemen",
    pendidikanS3: "Doktor Ilmu Pendidikan",
  },
  {
    NIDN: "8888290019 ",
    namaDosen: "YURMAN ZAINAL",
    namaDosenGelar: "Dr. Yurman Zainal, S.Pd., M.M.",
    programStudi: "Teknik Informatika (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "01 Agustus 2018",
    pendidikanS2: "Magister Manajemen",
    pendidikanS3: "Doktor - Ilmu Pendidikan",
  },
  {
    NIDN: "0409069602",
    NUPTK: "6941773674130262",
    namaDosen: "ZAENAL ALAMSYAH",
    namaDosenGelar: "Zaenal Alamsyah, S.Kom., M.Kom.",
    programStudi: "Teknik Informatika (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 April 2023",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 September 2023",
    pendidikanS2: "Magister Komputer",
  },
  {
    NIDN: "0410107806",
    NUPTK: "7342756657130243",
    namaDosen: "ZELDI SURYADY",
    namaDosenGelar: "Zeldy Suryady, S.T., M.Si.",
    programStudi: "Informatika (S2)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "20 Maret 2016",
    pendidikanS2: "Master of Science",
    pendidikanS3: "Doktor Komputer science",
  },
  {
    NIDN: "0425068002",
    NUPTK: "4838749651200042",
    namaDosen: "ODI AKHYARSI",
    namaDosenGelar: "Dr. Eng. Odi Akhyarsi, S.T., M.Eng.",
    programStudi: "Teknik Mesin (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "1 Janurari 2024",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "01 Mei 2024",
    pendidikanS2: "Master of Engineering",
    pendidikanS3: "Doctor of Engineering",
  },
  {
    NIDN: "0120240040",
    namaDosen: "ABD RAHMAN BIN ABDUL RAHIM",
    programStudi: "Teknik Mesin (S1)",
    jabatanAkademik: "Lektor Kepala",
    tmtJad: "26 Februari 2007",
    pendidikanS2: "Master of Science",
    pendidikanS3: "Doctor Of Pholosophy",
  },
  {
    NIDN: "0428118903",
    NUPTK: "7460767668131103",
    namaDosen: "AGUSTAMI SITORUS",
    namaDosenGelar: "Agustami Sitorus, S.TP., M.Sc.",
    programStudi: "Teknik Mesin (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 Agustus 2018",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 Januari 2019",
    pendidikanS2: "Master of Science",
  },
  {
    NIDN: "0417118205",
    namaDosen: "ANDI RINALDI HASAN",
    namaDosenGelar: "Andi Rinaldi Hasan, S.T., M.T.",
    programStudi: "Teknik Mesin (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 Mei 2017",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 Juli 2017",
  },
  {
    NIDN: "0424038703 ",
    namaDosen: "ARIES KARYADI",
    namaDosenGelar: "Aries Karyadi, S.T., M.T.",
    programStudi: "Teknik Mesin (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 Agustus 2018",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 Januari 2019",
  },
  {
    NIDN: "0325127607",
    NUPTK: "9557754655130153",
    namaDosen: "CHRIS SALIM",
    namaDosenGelar: "Dr. Eng. Chris Salim, B.Eng., M.Eng.",
    programStudi: "Teknik Mesin (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "02 Agustus 2021",
    pendidikanS2: "Master of Engineering",
    pendidikanS3: "Doctor of Engineering",
  },
  {
    NIDN: "0429038703",
    NUPTK: "6661766667130152",
    namaDosen: "DANI MARDIYANA",
    namaDosenGelar: "Dani Mardiyana, S.Pd., M.T.",
    programStudi: "Teknik Mesin (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 Desember 2024",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "01 Januari 2026",
    pendidikanS2: "Magister Teknik",
  },
  {
    NIDN: "0423119002",
    NUPTK: "5455768669130283",
    namaDosen: "DODI IWAN SUMARNO",
    namaDosenGelar: "Dodi Iwan Sumarno, S.T., M.T.",
    programStudi: "Teknik Mesin (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 Maret 2021",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 Desember 2021",
    pendidikanS2: "Magister Teknik",
  },
  {
    NIDN: "0424089501",
    NUPTK: "4156773674230243",
    namaDosen: "DWI MARDIKA LESTARI",
    namaDosenGelar: "Dwi Mardika Lestari, S.T., M.Sc.",
    programStudi: "Teknik Mesin (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 Agustus 2025",
    pendidikanS2: "Master of Science",
  },
  {
    NIDN: "0406029002",
    NUPTK: "1538768669130302",
    namaDosen: "FABROBI FAZLUR RIDHA",
    namaDosenGelar: "Fabrobi Fazlur Ridha, B.Eng., M.T.",
    programStudi: "Teknik Mesin (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 Januari 2023",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    pendidikanS2: "Magister Teknik",
  },
  {
    NIDN: "0422098102",
    NUPTK: "7254759660210073",
    namaDosen: "HEPPI FAMILIANA",
    namaDosenGelar: "Heppi Familiana, S.ST., M.T.",
    programStudi: "Teknik Mesin (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 Agustus 2018",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    pendidikanS2: "Magister Teknik",
  },
  {
    NIDN: "0415039402",
    NUPTK: "9647772673130272",
    namaDosen: "LAZUARDI AKMAL ISLAMI",
    namaDosenGelar: "Lazuardi Akmal Islami, S.Si., M.Si.",
    programStudi: "Teknik Mesin (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 Juni 2025",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "01 Januari 2026",
    pendidikanS2: "Magister Sains",
    jabatan_struktural: "Ketua Prodi Teknik Mesin",
  },
  {
    NIDN: "0418028708",
    NUPTK: "1550765666130292",
    namaDosen: "MOCHAMMAD ARVIN SYARIFUDDIN",
    namaDosenGelar: "Mochammad Arvin Syarifuddin, S.T., M.T.",
    programStudi: "Teknik Mesin (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 Juni 2021",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 November 2023",
    pendidikanS2: "Magister Teknik",
  },
  {
    NIDN: "8809290019",
    NUPTK: "4838749651200042",
    namaDosen: "MULYADI",
    namaDosenGelar: "Mulyadi, S.Pd., M.T.",
    programStudi: "Teknik Mesin (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 Juni 2019",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 November 2019",
    pendidikanS2: "Magister Teknik",
  },
  {
    NIDN: "0120240039",
    namaDosen: "SIVAKUMAR NALAPPAN SELLAPPAN",
    programStudi: "Teknik Mesin (S1)",
    jabatanAkademik: "Lektor Kepala",
    pendidikanS2: "Master Of Engineering",
    pendidikanS3: "Doktor of Philosophy",
  },
  {
    NIDN: "9904020037 ",
    namaDosen: "SRIYONO",
    namaDosenGelar: "Sriyono, S.Pd., M.T.",
    programStudi: "Teknik Mesin (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "01 Agustus 2016",
    pendidikanS2: "Magister Teknik",
  },
  {
    NIDN: "0410109701",
    NUPTK: "4838749651200042",
    namaDosen: "ZAID SULAIMAN",
    namaDosenGelar: "Zaid Sulaiman, S.T., M.T.",
    programStudi: "Teknik Mesin (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 Maret 2025",
    Inpassing: "Penata golongan ruang III/c",
    tmtInpassing: "01 Januari 2026",
    pendidikanS2: "Magister Teknik",
  },
  {
    NIDN: "0410059401",
    NUPTK: "3842772673130322",
    namaDosen: "ARDIN ROZANDI",
    namaDosenGelar: "Ardin Rozandi, S.T., M.T.",
    programStudi: "Teknik Sipil (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 April 2023",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 September 2023",
    pendidikanS2: "Magister Teknik",
  },
  {
    NIDN: "0405036803",
    namaDosen: "ANDRIJANTO",
    programStudi: "Teknik Sipil (S1)",
    jabatanAkademik: "Tenaga Pengajar",
  },
  {
    NIDN: "8963060022",
    namaDosen: "AKHMAD ZAENAL ABIDIN",
    namaDosenGelar: "Dr. H. Akhmad Zaenal Abidin, S.Pd., M.Pd.",
    programStudi: "Teknik Sipil (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    pendidikanS2: "Magister Pendidikan",
    pendidikanS3: "Doktor Teknologi Pendidikan",
  },
  {
    NIDN: "8875580018",
    NUPTK: "9650745647200032",
    namaDosen: "BAMBANG JATMIKA",
    namaDosenGelar: "Bambang Jatmika, S.ST., M.T.",
    programStudi: "Teknik Sipil (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 Februari 2021",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 Desember 2021",
    pendidikanS2: "Magister Teknik",
  },
  {
    NIDN: "8866501019",
    NUPTK: "1242754655130143",
    namaDosen: "CECE SUHENDI",
    namaDosenGelar: "Cece Suhendi, S.T., M.T.",
    programStudi: "Teknik Sipil (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 Maret 2021",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 Desember 2021",
    pendidikanS2: "Magister Teknik",
  },
  {
    NIDN: "0416038503",
    NUPTK: "2648763664131072",
    namaDosen: "DANIEL ARIE SUSANTO",
    namaDosenGelar: "Daniel Arie Susanto, S.T., M.T.",
    programStudi: "Teknik Sipil (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 September 2022",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 Desember 2022",
    pendidikanS2: "Magister Teknik",
  },
  {
    NIDN: "0412099205",
    namaDosen: "DANANG PURWANTO",
    namaDosenGelar: "Danang Purwanto, S.T., M.Eng.",
    programStudi: "Teknik Sipil (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "14 Februari 2022",
    pendidikanS2: "Master Of Engineering",
  },
  {
    NIDN: "0404069001 ",
    namaDosen: "DEBBY RAHMAWATI, S.T.,M.T",
    namaDosenGelar: "Debby Rahmawati, S.T., M.T.",
    programStudi: "Teknik Sipil (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 Januari 2017",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b;",
    tmtInpassing: "01 Juli 2017",
  },
  {
    NIDN: "0413128903",
    namaDosen: "DEWI SARTIKA",
    namaDosenGelar: "Dewi Sartika T., S.TP., M.Si.",
    programStudi: "Teknik Sipil (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 Agustus 2018",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b;",
    tmtInpassing: "01 Januari 2019",
  },
  {
    NIDN: "0416039303",
    NUPTK: "5648771672130302",
    namaDosen: "DIO DAMAS PERMADI",
    namaDosenGelar: "Dio Damas Permadi, S.T., M.Eng.",
    programStudi: "Teknik Sipil (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 April 2024",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b;",
    tmtInpassing: "01 September 2024",
    pendidikanS2: "Master of Engineering",
  },
  {
    NIDN: "8932060022",
    namaDosen: "FURTASIH",
    namaDosenGelar: "Dr. Furtasih, S.Pd., M.Pd.",
    programStudi: "Teknik Sipil (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "23 Agustus 2021",
    pendidikanS2: "Magister Pendidkan",
    pendidikanS3: "Doktor Teknologi Pendidikan",
  },
  {
    NIDN: "8900060022",
    NUPTK: "8158759660230123",
    namaDosen: "ENENG RAHMI",
    namaDosenGelar: "Dr. Eneng Rahmi, S.Si. M.Si.",
    programStudi: "Teknik Sipil (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "24 Juli 2023",
    pendidikanS2: "s",
    pendidikanS3: "Doktor Ilmu Lingkungan",
  },
  {
    NIDN: "0408088901",
    namaDosen: "HASAN BASRI MAULANA, S.T.,M.T",
    namaDosenGelar: "Hasan Basri Maulana, S.T., M.T.",
    programStudi: "Teknik Sipil (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 Januari 2017",
    Inpassing: "Penata Muda Tk. I, Golongan ruang III/b",
    tmtInpassing: "01 Maret 2017",
  },
  {
    NIDN: "8942060022",
    namaDosen: "HUJAIR FAIZAN",
    namaDosenGelar: "Dr. Hujair Faizan, S.H., M.Pd.",
    programStudi: "Teknik Sipil (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "23 Agustus 2021",
    pendidikanS2: "Magister Pendidikan",
    pendidikanS3: "Doktor Teknologi Pendidikan",
  },
  {
    NIDN: "8890070018",
    NUPTK: "6433754657200032",
    namaDosen: "JASMANSYAH",
    namaDosenGelar: "Jasmansyah, M.Pd.",
    programStudi: "Teknik Sipil (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 April 2019",
    pendidikanS2: "Magister Pendidikan",
    pendidikanS3: "Doktor Pendidikan",
  },
  {
    NIDN: "0429099603",
    NUPTK: "8261774675230233",
    namaDosen: "LIOBA EVITA ANIKUSUMA",
    namaDosenGelar: "Lioba Evita Anikusuma, S.T., M.T.",
    programStudi: "Teknik Sipil (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 Juni 2025",
    Inpassing: "Penata Muda Tk. I, Golongan ruang III/b",
    tmtInpassing: "01 Juli 2025",
    pendidikanS2: "Magister Teknik",
  },
  {
    NIDN: "892006002",
    namaDosen: "MARJUKI",
    programStudi: "Teknik Sipil (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    pendidikanS2: "Magister Manajemen Pendidikan",
    pendidikanS3: "Doktor Pendidikan",
  },
  {
    NIDN: "0423049001",
    namaDosen: "MUHAMMAD AMMAR",
    namaDosenGelar: "Muhammad Ammar, S.T., M.T.",
    programStudi: "Teknik Sipil (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 Januari 2017",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 Maret 2017",
  },
  {
    NIDN: "0414119701",
    NUPTK: "2446775676130153",
    namaDosen: "MUHAMMAD HIDAYAT",
    namaDosenGelar: "Muhammad Hidayat, M.Eng.",
    programStudi: "Teknik Sipil (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 Agustus 2025",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 September 2023",
    pendidikanS2: "Master of Engineering",
  },
  {
    NIDN: "0120240016",
    namaDosen: "MUHAMMAD SUBANDI",
    namaDosenGelar: "Dr. Ir. Drs. H. M. Subandi, M.P.",
    programStudi: "Teknik Sipil (S1)",
    jabatanAkademik: "Profesor",
    pendidikanS2: "Magister Pertanian",
    pendidikanS3: "Doktor Ilmu Pertanian",
  },
  {
    NIDN: "0420119702",
    NUPTK: "5452775676130163",
    namaDosen: "NADHYA SUSILO NUGROHO",
    namaDosenGelar: "Nadhya Susilo Nugroho, S.T., M.T.",
    programStudi: "Teknik Sipil (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 Agustus 2025",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 September 2025",
    pendidikanS2: "Magister Teknik",
  },
  {
    NIDN: "0403029301",
    NUPTK: "3535771672230272",
    namaDosen: "NITA KURNITA SARI",
    programStudi: "Teknik Sipil (S1)",
    jabatanAkademik: "Tenaga Pengajar",
    tmtJad: "18 September 2023",
    pendidikanS2: "Master of Engineering",
  },
  {
    NIDN: "0402037401",
    NUPTK: "7634752653130112",
    namaDosen: "PAIKUN",
    namaDosenGelar: "Paikun, S.T., M.T.",
    programStudi: "Teknik Sipil (S1)",
    jabatanAkademik: "Lektor",
    tmtJad: "01 Agustus 2023",
    Inpassing: "Penata, golongan ruang III/c",
    tmtInpassing: "01 Januari 2024",
    pendidikanS2: "Magister Teknik",
  },
  {
    NIDN: "0413098004",
    namaDosen: "RICHA RAHMALIYA SUNHADJI",
    namaDosenGelar: "Richa Rahmaliya Sunhadji, S.T., M.T.",
    programStudi: "Teknik Sipil (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 Juni 2023",
    pendidikanS2: "Magister Teknik",
  },
  {
    NIDN: "0418099001",
    namaDosen: "RICO SIHOTANG, S.T.,M.T",
    namaDosenGelar: "Rico Sihotang, S.T., M.T.",
    programStudi: "Teknik Sipil (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 Januari 2017",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 Maret 2017",
  },
  {
    NIDN: "0402109401",
    NUPTK: "2334772673130253",
    namaDosen: "SELFIN ANUGRAH AMDANI",
    namaDosenGelar: "Selfin Anugrah Amdani, S.T., M.T.",
    programStudi: "Teknik Sipil (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 April 2023",
    pendidikanS2: "Magister Teknik",
  },
  {
    NIDN: "0422048703",
    NUPTK: "2754765666137012",
    namaDosen: "TRIONO",
    namaDosenGelar: "Triono, S.Pd., M.T.",
    programStudi: "Teknik Sipil (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 Januari 2023",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 Mei 2023",
  },
  {
    NIDN: "0422108804",
    NUPTK: "1354766667230273",
    namaDosen: "UTAMY SUKMAYU SAPUTRI",
    namaDosenGelar: "Utamy Sukmayu Saputri, S.T., M.T.",
    programStudi: "Teknik Sipil (S1)",
    jabatanAkademik: "Asisten Ahli",
    tmtJad: "01 Januari 2024",
    Inpassing: "Penata Muda Tk. I, golongan ruang III/b",
    tmtInpassing: "01 Mei 2024",
    pendidikanS2: "Magister Teknik",
    jabatan_struktural: "Ketua Prodi Teknik Sipil",
  },
  {
    NIDN: "012025013",
    namaDosen: "WILLIAMS DUNU",
    programStudi: "Teknik Sipil (S1)",
    jabatanAkademik: "Lektor Kepala",
    tmtJad: "09 Januari 2025",
    pendidikanS2: "Master Of Science Constructor Technology",
    pendidikanS3: "Doctor Of Philosophy",
  },
];
